package com.ttdev.sp;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-24T10:42:23.953-08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ttdev.com/sp", name = "StatProducer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StatProducer {

    @Oneway
    @WebMethod(action = "http://ttdev.com/sp/NewOperation")
    public void getStatistics(
        @WebParam(partName = "parameters", name = "getStatistics", targetNamespace = "http://ttdev.com/sp")
        java.lang.String parameters
    );
}
