INSERT  INTO `vzdn_sys_roles` (`role_id`,`role_name`,`role_description`,`type_id`,`created_by`,`created_date`,`last_updated_by`,`last_updated_date`,`vzdn_role_mapping_id`) VALUES
(7,'Read Only for BREW','Read Only for BREW',2,NULL,NULL,NULL,NULL,2001),
(8,'WAP Biz Dev','WAP Biz Dev',2,NULL,NULL,NULL,NULL,2002),
(9,'WAP Product Development','WAP Product Development',2,NULL,NULL,NULL,NULL,2003),
(10,'WAP Technology Development','WAP Technology Development',2,NULL,NULL,NULL,NULL,2004),
(11,'Intertek','Intertek',2,NULL,NULL,NULL,NULL,2005),
(12,'VZAppZone Admin','VZAppZone Admin',2,NULL,NULL,NULL,NULL,2006),
(13,'Dashboard Admin','Dashboard Admin',2,NULL,NULL,NULL,NULL,2007),
(14,'Wireless Developer','Wireless Developer',2,NULL,NULL,NULL,NULL,2008),
(15,'BREW Admin','BREW Admin',2,NULL,NULL,NULL,NULL,2009),
(16,'Legal','Legal',2,NULL,NULL,NULL,NULL,2010),
(17,'SUPERUSER','SUPERUSER',2,NULL,NULL,NULL,NULL,2011),
(18,'VZWADMIN','VZWADMIN',2,NULL,NULL,NULL,NULL,2012),
(19,'WAP Admin','WAP Admin',2,NULL,NULL,NULL,NULL,2014),
(20,'Enterprise Admin','Enterprise Admin',2,NULL,NULL,NULL,NULL,2015),
(21,'Tech Team','Tech Team',2,NULL,NULL,NULL,NULL,2016),
(22,'JMA Contract Admin','JMA Contract Admin',2,NULL,NULL,NULL,NULL,2017),
(23,'Super','Super',2,NULL,NULL,NULL,NULL,2018),
(24,'WAP - Read only','WAP - Read only',2,NULL,NULL,NULL,NULL,2019),
(25,'Evaluation','Evaluation',2,NULL,NULL,NULL,NULL,2020),
(26,'Biz Dev BREW Admin','Biz Dev BREW Admin',2,NULL,NULL,NULL,NULL,2021),
(27,'Read Only','Read Only',2,NULL,NULL,NULL,NULL,2022),
(28,'Rollback_DCR','Rollback_DCR',2,NULL,NULL,NULL,NULL,2023),
(29,'BREW - Read only','BREW - Read only',2,NULL,NULL,NULL,NULL,2024);