//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 08:38:24 AM VET 
//


package com.netpace.aims.ws.amdocs.partner;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentProviderDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentProviderDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contactData" type="{http://api.qpass.com/cponboarding}ContactDataType" maxOccurs="unbounded"/>
 *         &lt;element name="remittanceInformationData" type="{http://api.qpass.com/cponboarding}RemittanceInformationDataType"/>
 *         &lt;element name="taxInformationData" type="{http://api.qpass.com/cponboarding}TaxInformationDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentProviderDataType", propOrder = {
    "contactData",
    "remittanceInformationData",
    "taxInformationData"
})
public class ContentProviderDataType {

    @XmlElement(required = true)
    protected List<ContactDataType> contactData;
    @XmlElement(required = true)
    protected RemittanceInformationDataType remittanceInformationData;
    @XmlElement(required = true)
    protected TaxInformationDataType taxInformationData;

    /**
     * Gets the value of the contactData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactDataType }
     * 
     * 
     */
    public List<ContactDataType> getContactData() {
        if (contactData == null) {
            contactData = new ArrayList<ContactDataType>();
        }
        return this.contactData;
    }

    /**
     * Gets the value of the remittanceInformationData property.
     * 
     * @return
     *     possible object is
     *     {@link RemittanceInformationDataType }
     *     
     */
    public RemittanceInformationDataType getRemittanceInformationData() {
        return remittanceInformationData;
    }

    /**
     * Sets the value of the remittanceInformationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemittanceInformationDataType }
     *     
     */
    public void setRemittanceInformationData(RemittanceInformationDataType value) {
        this.remittanceInformationData = value;
    }

    /**
     * Gets the value of the taxInformationData property.
     * 
     * @return
     *     possible object is
     *     {@link TaxInformationDataType }
     *     
     */
    public TaxInformationDataType getTaxInformationData() {
        return taxInformationData;
    }

    /**
     * Sets the value of the taxInformationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxInformationDataType }
     *     
     */
    public void setTaxInformationData(TaxInformationDataType value) {
        this.taxInformationData = value;
    }

}
