//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 08:38:24 AM VET 
//


package com.netpace.aims.ws.amdocs.partner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CPOnboardingDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CPOnboardingDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="initialProfileData" type="{http://api.qpass.com/cponboarding}InitialProfileDataType"/>
 *         &lt;element name="contentProviderData" type="{http://api.qpass.com/cponboarding}ContentProviderDataType"/>
 *         &lt;element name="externalInformationList" type="{http://api.qpass.com/cponboarding}ExternalInformationList" minOccurs="0"/>
 *         &lt;element name="provisingData" type="{http://api.qpass.com/cponboarding}ProvisioningDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CPOnboardingDataType", propOrder = {
    "initialProfileData",
    "contentProviderData",
    "externalInformationList",
    "provisingData"
})
public class CPOnboardingDataType {

    @XmlElement(required = true)
    protected InitialProfileDataType initialProfileData;
    @XmlElement(required = true)
    protected ContentProviderDataType contentProviderData;
    protected ExternalInformationList externalInformationList;
    protected ProvisioningDataType provisingData;

    /**
     * Gets the value of the initialProfileData property.
     * 
     * @return
     *     possible object is
     *     {@link InitialProfileDataType }
     *     
     */
    public InitialProfileDataType getInitialProfileData() {
        return initialProfileData;
    }

    /**
     * Sets the value of the initialProfileData property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialProfileDataType }
     *     
     */
    public void setInitialProfileData(InitialProfileDataType value) {
        this.initialProfileData = value;
    }

    /**
     * Gets the value of the contentProviderData property.
     * 
     * @return
     *     possible object is
     *     {@link ContentProviderDataType }
     *     
     */
    public ContentProviderDataType getContentProviderData() {
        return contentProviderData;
    }

    /**
     * Sets the value of the contentProviderData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentProviderDataType }
     *     
     */
    public void setContentProviderData(ContentProviderDataType value) {
        this.contentProviderData = value;
    }

    /**
     * Gets the value of the externalInformationList property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalInformationList }
     *     
     */
    public ExternalInformationList getExternalInformationList() {
        return externalInformationList;
    }

    /**
     * Sets the value of the externalInformationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalInformationList }
     *     
     */
    public void setExternalInformationList(ExternalInformationList value) {
        this.externalInformationList = value;
    }

    /**
     * Gets the value of the provisingData property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisioningDataType }
     *     
     */
    public ProvisioningDataType getProvisingData() {
        return provisingData;
    }

    /**
     * Sets the value of the provisingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisioningDataType }
     *     
     */
    public void setProvisingData(ProvisioningDataType value) {
        this.provisingData = value;
    }

}
