//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 08:38:24 AM VET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.qpass.com/cponboarding", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.netpace.aims.ws.amdocs.partner;
