//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 08:38:24 AM VET 
//


package com.netpace.aims.ws.amdocs.partner;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxInformationDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxInformationDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isTaxNexusExempted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="nexus" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxInformationDataType", propOrder = {
    "isTaxNexusExempted",
    "nexus"
})
public class TaxInformationDataType {

    protected boolean isTaxNexusExempted;
    protected List<String> nexus;

    /**
     * Gets the value of the isTaxNexusExempted property.
     * 
     */
    public boolean isIsTaxNexusExempted() {
        return isTaxNexusExempted;
    }

    /**
     * Sets the value of the isTaxNexusExempted property.
     * 
     */
    public void setIsTaxNexusExempted(boolean value) {
        this.isTaxNexusExempted = value;
    }

    /**
     * Gets the value of the nexus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nexus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNexus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNexus() {
        if (nexus == null) {
            nexus = new ArrayList<String>();
        }
        return this.nexus;
    }

}
