package com.ttdev.sp;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Dec 21 15:53:54 HKT 2009
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://ttdev.com/sp", name = "StatProducer")
@XmlSeeAlso({ObjectFactory.class})
public interface StatProducer {

    @Oneway
    @RequestWrapper(localName = "getStatistics", targetNamespace = "http://ttdev.com/sp", className = "com.ttdev.sp.GetStatistics")
    @WebMethod(action = "http://ttdev.com/sp/NewOperation")
    public void getStatistics(
        @WebParam(name = "param", targetNamespace = "")
        java.lang.String param,
        @WebParam(name = "replyTo", targetNamespace = "")
        java.lang.String replyTo
    );
}
