package com.ttdev.ss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-24T10:22:38.028-08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ttdev.com/ss", name = "StatService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StatService {

    @WebResult(name = "getStatisticsResponse", targetNamespace = "http://ttdev.com/ss", partName = "parameters")
    @WebMethod(action = "http://ttdev.com/ss/NewOperation")
    public java.lang.String getStatistics(
        @WebParam(partName = "parameters", name = "getStatistics", targetNamespace = "http://ttdev.com/ss")
        java.lang.String parameters
    );
}
