package spring.by.example.hibernate.model;

// Generated Mar 30, 2013 10:30:20 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer personId;
	private String firstName;
	private String lastName;
	private Date created;
	private Set<Address> addresses = new HashSet<Address>(0);

	public Person() {
	}

	public Person(String firstName, String lastName, Date created) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.created = created;
	}

	public Person(String firstName, String lastName, Date created,
			Set<Address> addresses) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.created = created;
		this.addresses = addresses;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	@Override
	public String toString() {
		return "Person [personId=" + personId + ", firstName=" + firstName
				+ ", lastName=" + lastName + ", created=" + created
				 + "]";
	}

}
