ALTER TABLE AIMS_APPS
        ADD (RING_TYPE_ID  NUMBER  DEFAULT 172)
/

ALTER TABLE AIMS_APPS ADD (
      CONSTRAINT FK_AIMS_APP_RING_TYPE 
      FOREIGN KEY (RING_TYPE_ID) 
      REFERENCES AIMS_TYPES (TYPE_ID))
/

--------------------------------------------------------------------------------
--Copy Ring Number from AIMS_JAVA_APPS to AIMS_APPS table.
--------------------------------------------------------------------------------
DECLARE

   CURSOR RING_NUM_RECS IS
    	SELECT AIMS_JAVA_APPS.RING_NUMBER,AIMS_JAVA_APPS.JAVA_APPS_ID 
          FROM AIMS_JAVA_APPS,AIMS_APPS
    	 WHERE AIMS_APPS.APPS_ID=AIMS_JAVA_APPS.JAVA_APPS_ID;

BEGIN

 FOR REC IN RING_NUM_RECS LOOP

   UPDATE AIMS_APPS
      SET RING_TYPE_ID=REC.RING_NUMBER
    WHERE APPS_ID = REC.JAVA_APPS_ID;
  COMMIT;

  END LOOP;

END;
/

ALTER TABLE AIMS_JAVA_APPS 
      DROP COLUMN RING_NUMBER
/

ALTER TABLE AIMS_JAVA_APPS DROP COLUMN RING_NUMBER;

INSERT INTO AIMS_PLACE_HOLDERS
   (PLACE_HOLDER_ID, PLACE_HOLDER_DISPLAY_NAME, CREATED_DATE, CREATED_BY, LAST_UPDATED_DATE, LAST_UPDATED_BY)
 VALUES
   (2002, 'ALLIANCE_SERVICE_FAILURE_CAUSE_MESSAGE', SYSDATE, 'system', SYSDATE, 'system')
/
   
INSERT INTO AIMS_EVENT_PLACE_HOLDERS
   (PLACE_HOLDER_ID, EVENT_ID)
 VALUES
   (2002, 2100)
/   
