------------------------------------------------------------------------
--create sequence for app ref id & contact ref id
------------------------------------------------------------------------
DROP SEQUENCE SEQ_APP_REF_ID;

CREATE SEQUENCE SEQ_APP_REF_ID
MINVALUE 5000000
MAXVALUE 999999999999999999999999999
START WITH 5000000
INCREMENT BY 1
CACHE 20;

DROP SEQUENCE SEQ_CONTRACT_REF_ID;

CREATE SEQUENCE SEQ_CONTRACT_REF_ID
MINVALUE 6000000
MAXVALUE 999999999999999999999999999
START WITH 6000000
INCREMENT BY 1
CACHE 20;

------------------------------------------------------------------------
-- Add columns to AIMS_CONTRACTS, AIMS_APPS, AIMS_WORKITEM
------------------------------------------------------------------------
ALTER TABLE AIMS_CONTRACTS
ADD ( RING_NUMBER NUMBER );

ALTER TABLE AIMS_CONTRACTS
ADD( CONTRACT_REF_ID NUMBER);

ALTER TABLE  AIMS_APPS
ADD (APP_REF_ID NUMBER);

ALTER TABLE AIMS_WORKITEM
ADD (ACTION_PAGE_URL VARCHAR2(500));

------------------------------------------------------------------------
--create Java apps table
------------------------------------------------------------------------
DROP TABLE AIMS_JAVA_APPS
;

CREATE TABLE AIMS_JAVA_APPS
( JAVA_APPS_ID               		NUMBER
, RING_NUMBER						NUMBER
, CONTENT_RATING_TYPE_ID   			NUMBER
, INFO_URL							VARCHAR2(150)
, ENTERPRISE_APP					VARCHAR2(1)
, APP_KEYWORD						VARCHAR2(50)
, APP_CATEGORY_TYPE_ID  			NUMBER
, APP_SUB_CATEGORY_TYPE_ID			NUMBER
, CONTRACT_ID						NUMBER
, MKTG_RELEASE						VARCHAR2(1)
, HR_PUBLISHER_LOGO         		BLOB
, HR_PUBLISHER_LOGO_FILE_NAME       VARCHAR2(150)
, HR_PUBLISHER_LOGO_CONTENT_TYPE	VARCHAR2(100)
, CHNL_TITLE_ICON                 	BLOB
, CHNL_TITLE_ICON_FILE_NAME       	VARCHAR2(150)
, CHNL_TITLE_ICON_CONTENT_TYPE    	VARCHAR2(100)
, SPLH_SCREEN_SHOT            		BLOB
, SPLH_SCREEN_SHOT_FILE_NAME      	VARCHAR2(150)
, SPLH_SCREEN_SHOT_CONTENT_TYPE     VARCHAR2(100)  
, ACTV_SCREEN_SHOT            		BLOB
, ACTV_SCREEN_SHOT_FILE_NAME        VARCHAR2(150)
, ACTV_SCREEN_SHOT_CONTENT_TYPE     VARCHAR2(100)  
, APP_SCREEN_SHOT            		BLOB
, APP_SCREEN_SHOT_FILE_NAME         VARCHAR2(150)
, APP_SCREEN_SHOT_CONTENT_TYPE      VARCHAR2(100)  
, APP_SCREEN_SHOT_1            		BLOB
, APP_SCREEN_SHOT_1_FILE_NAME       VARCHAR2(150)
, APP_SCREEN_SHOT_1_CONTENT_TYPE    VARCHAR2(100)  
, APP_SCREEN_SHOT_2            		BLOB
, APP_SCREEN_SHOT_2_FILE_NAME       VARCHAR2(150)
, APP_SCREEN_SHOT_2_CONTENT_TYPE    VARCHAR2(100)  
, APP_SCREEN_SHOT_3            	  	BLOB
, APP_SCREEN_SHOT_3_FILE_NAME       VARCHAR2(150)
, APP_SCREEN_SHOT_3_CONTENT_TYPE    VARCHAR2(100)  
, APP_SCREEN_SHOT_4            		BLOB
, APP_SCREEN_SHOT_4_FILE_NAME       VARCHAR2(150)
, APP_SCREEN_SHOT_4_CONTENT_TYPE    VARCHAR2(100)  
, FAQ_FILE		            		BLOB
, FAQ_FILE_FILE_NAME          		VARCHAR2(150)
, FAQ_FILE_CONTENT_TYPE       		VARCHAR2(100)  
, TECH_CONTACT_ID					NUMBER       
, TECH_CONTACT_FIRST_NAME       	VARCHAR2(100)
, TECH_CONTACT_LAST_NAME          	VARCHAR2(200)
, TECH_CONTACT_TITLE              	VARCHAR2(200)
, TECH_CONTACT_EMAIL_ADDRESS      	VARCHAR2(200)
, TECH_CONTACT_PHONE              	VARCHAR2(50)
, TECH_CONTACT_MOBILE             	VARCHAR2(50)
, COMPANY_LOGO            			BLOB
, COMPANY_LOGO_FILE_NAME    		VARCHAR2(150)
, COMPANY_LOGO_CONTENT_TYPE    		VARCHAR2(100)
, APPLICATION_NAME					VARCHAR2(200)
, APP_TITLE_NAME                	BLOB
, APP_TITLE_NAME_FILE_NAME      	VARCHAR2(150)
, APP_TITLE_NAME_CONTENT_TYPE   	VARCHAR2(100)
, PRODUCT_DESCRIPTION				VARCHAR2(1000)
, APP_SCREEN_SHOT_5            		BLOB
, APP_SCREEN_SHOT_5_FILE_NAME       VARCHAR2(150)
, APP_SCREEN_SHOT_5_CONTENT_TYPE    VARCHAR2(100)  
, APP_SCREEN_SHOT_6            		BLOB
, APP_SCREEN_SHOT_6_FILE_NAME       VARCHAR2(150)
, APP_SCREEN_SHOT_6_CONTENT_TYPE    VARCHAR2(100)  
, APP_SCREEN_SHOT_7            		BLOB
, APP_SCREEN_SHOT_7_FILE_NAME       VARCHAR2(150)
, APP_SCREEN_SHOT_7_CONTENT_TYPE    VARCHAR2(100)  
, APP_SCREEN_SHOT_8            		BLOB
, APP_SCREEN_SHOT_8_FILE_NAME       VARCHAR2(150)
, APP_SCREEN_SHOT_8_CONTENT_TYPE    VARCHAR2(100)  
, APP_SCREEN_SHOT_9            		BLOB
, APP_SCREEN_SHOT_9_FILE_NAME       VARCHAR2(150)
, APP_SCREEN_SHOT_9_CONTENT_TYPE    VARCHAR2(100)  
, USING_APPLICATION               	CLOB
, TIPS_AND_TRICKS                 	CLOB
, FAQ							  	CLOB
, TROUBLESHOOTING                 	CLOB
, DEVELOPMENT_COMPANY_DISCLAIMER  	CLOB
, ADDITIONAL_INFORMATION          	CLOB
, APP_CATEGORY_1_TYPE_ID  			NUMBER
, APP_SUB_CATEGORY_1_TYPE_ID		NUMBER
, APP_CATEGORY_2_TYPE_ID  			NUMBER
, APP_SUB_CATEGORY_2_TYPE_ID		NUMBER
, CONTENT_TYPE_ID					NUMBER					
, VZW_PROJECTED_LIVE_DATE			DATE
, ENTERPRISE_ID						VARCHAR2(100)
, NOTES								VARCHAR2(1000)
, TAX_CATEGORY_CODE_ID				NUMBER
, CONTRACT_REF_ID 					NUMBER
, APP_REF_ID 						NUMBER
);

ALTER TABLE AIMS_JAVA_APPS ADD (
  PRIMARY KEY
 (JAVA_APPS_ID)  
);

ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_APPS_1 
 FOREIGN KEY (JAVA_APPS_ID) 
 REFERENCES AIMS_APPS (APPS_ID)
);

ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_CONTENT_RATING 
 FOREIGN KEY (CONTENT_RATING_TYPE_ID) 
 REFERENCES AIMS_TYPES (TYPE_ID)
);
 
--ALTER TABLE AIMS_JAVA_APPS ADD (
--  CONSTRAINT UNIQUE_JAVA_APP_KEYWORD
-- UNIQUE (APP_KEYWORD) 
--);
 
--ALTER TABLE AIMS_JAVA_APPS ADD (
--  CONSTRAINT UNIQUE_JAVA_ENTERPRISE_ID
-- UNIQUE (ENTERPRISE_ID) 
--);

ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_CATEGORY_TYPE
 FOREIGN KEY (APP_CATEGORY_TYPE_ID) 
 REFERENCES AIMS_TYPES (TYPE_ID)
);

ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_SUB_CATEGORY_TYPE 
 FOREIGN KEY (APP_SUB_CATEGORY_TYPE_ID) 
 REFERENCES AIMS_TYPES (TYPE_ID)
);
 
ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_CATEGORY_TYPE1
 FOREIGN KEY (APP_CATEGORY_1_TYPE_ID) 
 REFERENCES AIMS_TYPES (TYPE_ID)
);

ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_SUB_CATEGORY_TYPE1 
 FOREIGN KEY (APP_SUB_CATEGORY_1_TYPE_ID) 
 REFERENCES AIMS_TYPES (TYPE_ID)
);
 
ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_CATEGORY_TYPE2
 FOREIGN KEY (APP_CATEGORY_2_TYPE_ID) 
 REFERENCES AIMS_TYPES (TYPE_ID)
);

ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_SUB_CATEGORY_TYPE2 
 FOREIGN KEY (APP_SUB_CATEGORY_2_TYPE_ID) 
 REFERENCES AIMS_TYPES (TYPE_ID)
);
 
ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_TAX_CATEGORY 
 FOREIGN KEY (TAX_CATEGORY_CODE_ID) 
 REFERENCES AIMS_TAX_CATEGORY_CODES (TAX_CATEGORY_CODE_ID)
);
 
ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_CONTENT_TYPE 
 FOREIGN KEY (CONTENT_TYPE_ID) 
 REFERENCES AIMS_TYPES (TYPE_ID)
);

ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_CONTRACT
 FOREIGN KEY (CONTRACT_ID) 
 REFERENCES AIMS_CONTRACTS (CONTRACT_ID)
);

------------------------------------------------------------------------
-- Create Index for Java Apps
------------------------------------------------------------------------
DROP INDEX FK_IND_AIMS_JAVA_APPS_CNT_RAT;
DROP INDEX FK_IND_AIMS_JAVA_APPS_CAT;
DROP INDEX FK_IND_AIMS_JAVA_APPS_SUB_CAT;
DROP INDEX FK_IND_AIMS_JAVA_APPS_CAT1;
DROP INDEX FK_IND_AIMS_JAVA_APPS_SUB_CAT1;
DROP INDEX FK_IND_AIMS_JAVA_APPS_CAT2;
DROP INDEX FK_IND_AIMS_JAVA_APPS_SUB_CAT2;
DROP INDEX FK_IND_AIMS_JAVA_APPS_TAX_CAT;
DROP INDEX FK_IND_AIMS_JAVA_APPS_CNT_TYPE;
DROP INDEX FK_IND_AIMS_JAVA_APPS_CNRT_ID;

CREATE INDEX FK_IND_AIMS_JAVA_APPS_CNT_RAT ON AIMS_JAVA_APPS (CONTENT_RATING_TYPE_ID);
CREATE INDEX FK_IND_AIMS_JAVA_APPS_CAT ON AIMS_JAVA_APPS (APP_CATEGORY_TYPE_ID);
CREATE INDEX FK_IND_AIMS_JAVA_APPS_SUB_CAT ON AIMS_JAVA_APPS (APP_SUB_CATEGORY_TYPE_ID);
CREATE INDEX FK_IND_AIMS_JAVA_APPS_CAT1 ON AIMS_JAVA_APPS (APP_CATEGORY_1_TYPE_ID);
CREATE INDEX FK_IND_AIMS_JAVA_APPS_SUB_CAT1 ON AIMS_JAVA_APPS (APP_SUB_CATEGORY_1_TYPE_ID);
CREATE INDEX FK_IND_AIMS_JAVA_APPS_CAT2 ON AIMS_JAVA_APPS (APP_CATEGORY_2_TYPE_ID);
CREATE INDEX FK_IND_AIMS_JAVA_APPS_SUB_CAT2 ON AIMS_JAVA_APPS (APP_SUB_CATEGORY_2_TYPE_ID);
CREATE INDEX FK_IND_AIMS_JAVA_APPS_TAX_CAT ON AIMS_JAVA_APPS (TAX_CATEGORY_CODE_ID);
CREATE INDEX FK_IND_AIMS_JAVA_APPS_CNT_TYPE ON AIMS_JAVA_APPS (CONTENT_TYPE_ID);
CREATE INDEX FK_IND_AIMS_JAVA_APPS_CNRT_ID ON AIMS_JAVA_APPS (CONTRACT_ID);
