package com.ttdev.sc;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Dec 21 15:53:54 HKT 2009
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://ttdev.com/sc", name = "StatConsumer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StatConsumer {

    @Oneway
    @WebMethod(action = "http://ttdev.com/sc/NewOperation")
    public void putStatistics(
        @WebParam(partName = "parameters", name = "putStatistics", targetNamespace = "http://ttdev.com/sc")
        java.lang.String parameters
    );
}
