
package com.ttdev.sc;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Dec 21 15:53:54 HKT 2009
 * Generated source version: 2.2.5
 * 
 */
 
public class StatConsumer_P1_Server{

    protected StatConsumer_P1_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new StatConsumerImpl();
        String address = "http://localhost:8081/sc/p1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new StatConsumer_P1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
