package com.netpace.device.enums;

public enum EventType {

    USER_ACCOUNT_VALIDATION_EVENT(1),
    PARTNER_REGISTERED(7),
    FORGOT_PASSWORD_EVENT(2),
    FORGOT_PASSWORD_UPDATED(29),
    FORGOT_USERNAME_EVENT(3),
    PASSWORD_UPDATED(30),
    USERNAME_UPDATED(31),
    PARTNER_USER_INVITED_EVENT(4),
    PARTNER_USER_INVITATION_ACCEPTED(32),
    PARTNER_USER_REQUESTS_TO_JOIN(33),
    PARTNER_USER_REQUEST_TO_JOIN_ACCEPTED(34),
    PARTNER_USER_REQUEST_TO_JOIN_REJECTED(88),
    VERIZON_USER_INVITED_EVENT(5),
    VERIZON_USER_INVITATION_ACCEPTED(35),
    PARTNER_UPDATED(36),
    PRODUCT_UPDATED(37),
    PARTNER_DELETED_EVENT(6),
    SEND_PRODUCTS_DETAIL_REPORT(39),
    SEND_PRODUCTS_TESTING_DETAIL_REPORT(40),
    SEND_COMPANY_DETAIL_REPORT(41),
    SEND_DEVELOPERS_WEEKLY_REPORT(42),
    SEND_DEVELOPERS_MONTHLY_REPORT(43),
    PRODUCT_DELETED(38),
    WORKITEM_DELAYED(91),
    EXCEPTION_EMAIL(44);


    private EventType(int id) {
        this.id = id;
    }
    private int id;

    public int getId() {
        return id;
    }
}
