package com.netpace.aims.ws.appinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.1
 * Thu May 07 13:34:55 PDT 2009
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.vzwdeveloper.com/vds/application/", name = "ApplicationInfoSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ApplicationInfoSoap {

    @WebResult(name = "ApplicationInfoResponse", targetNamespace = "http://www.vzwdeveloper.com/vds/application/", partName = "parameters")
    @WebMethod(action = "http://www.vzwdeveloper.com/VDS/getApplicationInfo")
    public ApplicationInfoResponse getApplicationInfo(
        @WebParam(partName = "parameters", name = "ApplicationInfoRequest", targetNamespace = "http://www.vzwdeveloper.com/vds/application/")
        ApplicationInfoRequest parameters
    ) throws ErrorSoapOut;
}
