delete from aims_role_privileges
where privilege_id = 300
/
delete from aims_notif_opt_in_recipients
/
update AIMS_BULLETINS
set is_active ='N'
where bulletin_id in (5,6) 
/
UPDATE AIMS_CONTRACTS S
   SET S.IS_CLICK_THROUGH_CONTRACT = 'N',
       S.RING_NUMBER = 172,
       S.CONTRACT_REF_ID = SEQ_CONTRACT_REF_ID.NEXTVAL
/
update AIMS_CONTRACTS
set is_click_through_contract = 'Y'
where contract_id in (186, 288, 196, 489) 
/
DECLARE
   CURSOR BUS_FUN_TST
   IS
      SELECT   A.CONTRACT_ID,A.HTML_FILE, A.HTML_FILE_FILE_NAME, A.HTML_FILE_CONTENT_TYPE
        FROM   AIMS_CONTRACTS_BAK A, AIMS_CONTRACTS B
       WHERE   A.CONTRACT_ID = B.CONTRACT_ID;
BEGIN
   FOR A IN BUS_FUN_TST
   LOOP
      UPDATE   AIMS_CONTRACTS
         SET   HTML_FILE = A.HTML_FILE,
               HTML_FILE_FILE_NAME = A.HTML_FILE_FILE_NAME,
               HTML_FILE_CONTENT_TYPE = A.HTML_FILE_CONTENT_TYPE
       WHERE   CONTRACT_ID = A.CONTRACT_ID;
      COMMIT;
   END LOOP;
END;
/
UPDATE AIMS_USERS
   SET USER_ACCOUNT_STATUS = 'DELETED'
 WHERE USER_ACCOUNT_STATUS = 'ONHOLD'
/
DELETE FROM AIMS_USER_ROLES R
      WHERE R.USER_ID IN
                    (SELECT   U.USER_ID
                       FROM   AIMS_USERS U
                      WHERE   USER_TYPE = 'V'
                        AND   USER_ACCOUNT_STATUS = 'DELETED')
/
Insert into AIMS_SYS_ROLES
   (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION, ROLE_TYPE, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE,vzdn_mapping_role_id)
 Values
   (240, 'Netpace Support Admin', 'Netpace Support Admin', 'V', 'admin@vzw.com', sysdate, 'admin@vzw.com', sysdate, 2026);
/
Insert into AIMS_ROLE_PRIVILEGES
   (ROLE_ID, PRIVILEGE_ID, IF_SELECT_ALLOWED, IF_CREATE_ALLOWED, IF_UPDATE_ALLOWED, IF_DELETE_ALLOWED)
 Values
   (240, 167, 'Y', 'Y', 'Y', 'Y');
/

   DECLARE
   CURSOR BUS_FUN_TST
   IS
      SELECT   U.ALLIANCE_ID,U.CONTACT_ID
        FROM   AIMS_USERS U, AIMS_CONTACTS C
       WHERE   U.CONTACT_ID = C.CONTACT_ID;
BEGIN
   FOR A IN BUS_FUN_TST
   LOOP
      UPDATE   AIMS_CONTACTS S
         SET   S.ALLIANCE_ID = A.ALLIANCE_ID
       WHERE   S.CONTACT_ID = A.CONTACT_ID;
      COMMIT;
   END LOOP;
END;
/
DECLARE
   CURSOR BUS_FUN_TST
   IS
      SELECT A.ALLIANCE_ID ALLIANCE_ID ,
             A.SALES_CONTACT_ID CONTACT_ID
        FROM AIMS_ALLIANCES A, AIMS_CONTACTS C
       WHERE A.SALES_CONTACT_ID = C.CONTACT_ID
       UNION ALL
      SELECT A.ALLIANCE_ID ALLIANCE_ID,
             A.TECH_CONTACT_ID CONTACT_ID
        FROM AIMS_ALLIANCES A, AIMS_CONTACTS C
       WHERE A.TECH_CONTACT_ID = C.CONTACT_ID
       UNION ALL
      SELECT A.ALLIANCE_ID ALLIANCE_ID,
             A.EXECUTIVE_CONTACT_ID CONTACT_ID
        FROM AIMS_ALLIANCES A, AIMS_CONTACTS C
       WHERE A.EXECUTIVE_CONTACT_ID = C.CONTACT_ID
       UNION ALL
      SELECT A.ALLIANCE_ID ALLIANCE_ID,
             A.BUS_CONTACT_ID CONTACT_ID
        FROM AIMS_ALLIANCES A, AIMS_CONTACTS C
       WHERE A.BUS_CONTACT_ID = C.CONTACT_ID;
       
BEGIN
   FOR A IN BUS_FUN_TST
   LOOP
      UPDATE   AIMS_CONTACTS S
         SET   S.ALLIANCE_ID = A.ALLIANCE_ID
       WHERE   S.CONTACT_ID = A.CONTACT_ID;
      COMMIT;
   END LOOP;
END;
/
DECLARE
   CURSOR BUS_FUN_TST
   IS
      SELECT U.ALLIANCE_ID ALLIANCE_ID,
             U.TECH_CONTACT_ID CONTACT_ID
        FROM AIMS_APPS U, AIMS_CONTACTS C
       WHERE U.TECH_CONTACT_ID = C.CONTACT_ID;
BEGIN
   FOR A IN BUS_FUN_TST
   LOOP
      UPDATE AIMS_CONTACTS S
         SET S.ALLIANCE_ID = A.ALLIANCE_ID
       WHERE S.CONTACT_ID = A.CONTACT_ID;
      COMMIT;
   END LOOP;
END;
/
UPDATE aims_countries aimscountry
   SET aimscountry.active_yn = 'N'
 WHERE aimscountry.country_id IN (21, 52, 54, 99, 100, 116, 196, 202, 232)
/
DECLARE
   CURSOR BUS_FUN_TST
   IS
      SELECT   S.ALLIANCE_ID
        FROM   AIMS_ALLIANCES S
       WHERE   S.STATUS = 'R';
BEGIN
   FOR A IN BUS_FUN_TST
   LOOP
      AIMS_ALLIANCES_PKG.delete_alliance (A.ALLIANCE_ID, 'TEST');
   END LOOP;
   COMMIT;
END;
/
UPDATE   AIMS_ALLIANCES
   SET   STATUS = 'R'
 WHERE   STATUS = 'S'
   AND   IS_JMA_ALLIANCE is NULL
/

