
package com.ttdev.biz;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-23T11:06:07.384-08:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "invalidProductId", targetNamespace = "http://foo.com")
public class QueryInvalidProductId extends Exception {
    
    private java.lang.String invalidProductId;

    public QueryInvalidProductId() {
        super();
    }
    
    public QueryInvalidProductId(String message) {
        super(message);
    }
    
    public QueryInvalidProductId(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryInvalidProductId(String message, java.lang.String invalidProductId) {
        super(message);
        this.invalidProductId = invalidProductId;
    }

    public QueryInvalidProductId(String message, java.lang.String invalidProductId, Throwable cause) {
        super(message, cause);
        this.invalidProductId = invalidProductId;
    }

    public java.lang.String getFaultInfo() {
        return this.invalidProductId;
    }
}
