package com.packtpub.springhibernate.model;

import com.packtpub.ch03.SetterInfoPrinter;

// Generated Mar 30, 2013 8:43:10 PM by Hibernate Tools 4.0.0

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer studentId;
	private String firstName;
	private String lastName;
	private SetterInfoPrinter printer;
	
	public Student() {
	}

	public Student(String firstName, String lastName) {
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		printer.print("setId", this.studentId, studentId);
		this.studentId = studentId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		printer.print("setFirstName", this.firstName, firstName);
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		printer.print("setLastName", this.lastName, lastName);
		this.lastName = lastName;
	}

	public SetterInfoPrinter getPrinter() {
		return printer;
	}

	public void setPrinter(SetterInfoPrinter printer) {
		this.printer = printer;
	}
	

}
