Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (82, 'New Alliances', 'New Alliances', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2, 'NEW_ALLIANCES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (83, 'Search Alliances', 'Search Alliances', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 3, 'SEARCH_ALLIANCES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (84, 'Alliance Summary', 'Alliance Summary', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 4, 'ALLIANCE_STATUS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (85, 'Company Information', 'Company Info', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 5, 'COMPANY_INFORMATION', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (86, 'Business Information', 'Business Info', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 6, 'BUSINESS_INFORMATION', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (87, 'Contact Information', 'Contact Info', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 7, 'CONTACT_INFORMATION', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (88, 'Alliance Contracts', 'Contracts', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 8, 'ALLIANCE_CONTRACTS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (90, 'Alliance Tools', 'Tools', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 10, 'SPOTLIGHT_PAGE', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (91, 'All Applications', 'All Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 11, 'ALL_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (92, 'Search Applications', 'Search Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 12, 'SEARCH_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (93, 'My Applications', 'My Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 13, 'MY_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (94, 'New Applications', 'New Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 14, 'NEW_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (95, 'Saved Applications', 'Saved Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 15, 'SAVED_APPLICATIONS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (144, 'My Alliances', 'My Alliances', 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 68, 'MY_ALLIANCES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (147, 'Manage Contracts', 'Manage Contracts', 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 69, 'MANAGE_CONTRACTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (148, 'Amendments', 'Amendments', 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 70, 'AMENDMENTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (150, 'Manage App Tab Manage Info', 'Manage App Tab Manage Info', 'system', TO_DATE('01/14/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('01/14/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_TAB_MANAGE_INFO', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (151, 'Legal User', 'Legal User', 'system', TO_DATE('01/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('01/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'LEGAL_USER', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (152, 'All Alliances', 'All Alliances', 'system', TO_DATE('01/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('01/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, 'ALL_ALLIANCES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (162, 'Manage Brew Apps', 'Manage Brew Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_BREW', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (163, 'Manage Enterprise Apps', 'Manage Enterprise Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_ENTERPRISE', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (164, 'Manage MMS Apps', 'Manage MMS Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_MMS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (165, 'Manage SMS Apps', 'Manage SMS Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_SMS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (166, 'Manage WAP Apps', 'Manage WAP Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_WAP', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (167, 'Manage Brew Related Information Section in Application''s Processing Information Page', 'Manage Brew Related Information Section in Application''s Processing Information Page', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/25/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_BREW_RELATED_INFO', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (168, 'Manage Assign Section in Application''s Processing Information Page', 'Manage Assign Section in Application''s Processing Information Page', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/25/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_ASSIGN', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (169, 'Manage Prioritization Section in Application''s Processing Information Page', 'Manage Prioritization Section in Application''s Processing Information Page', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/25/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_PRIORITIZATION', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (170, 'Manage Testing Section in Application''s Processing Information Page', 'Manage Testing Section in Application''s Processing Information Page', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/25/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_TESTING', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (171, 'Manage Brew Production Information Section in Application''s Processing Information Page', 'Manage Brew Production Information Section in Application''s Processing Information Page', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/25/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_BREW_PROD_INFO', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (172, 'Inbox', 'Inbox', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 21, 'INBOX', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (173, 'Outbox', 'Outbox', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 22, 'OUTBOX', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (174, 'Users', 'Users', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 38, 'USERS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (175, 'Roles', 'Roles', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 37, 'ROLES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (176, 'Upload NSTL Data', 'Upload NSTL Data', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 17, 'UPLOAD_NSTL_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (177, 'Devices', 'Devices', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 48, 'DEVICES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (178, 'Application Categories', 'Application Categories', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 49, 'APP_CATEGORIES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (179, 'Application Subcategories', 'Application Subcategories', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 50, 'APP_SUB_CATEGORIES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (180, 'Tools', 'Tools', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 51, 'TOOLS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (181, 'Email Messages', 'Email Messages', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 52, 'EMAIL_MESSAGES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (182, 'Email Groups', 'Email Groups', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 53, 'EMAIL_GROUPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (183, 'Sales Contacts', 'Sales Contacts', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 54, 'SALES_CONTACTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (184, 'Devices on Loan', 'Devices on Loan', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 15, 'DEVICES_ON_LOAN', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (185, 'User Defined Report', 'User Defined Report', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 10, 'UREPORTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (186, 'Discussion Forum', 'Discussion Forum', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 29, 'FORUM', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (187, 'View FAQ', 'View FAQ', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 31, 'FAQ', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (188, 'View Hot Topics', 'View Hot Topics', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 32, 'TOPICS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (189, 'Submit Sales Lead', 'Submit Sales Lead', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 79, 'SUBMIT_SALES_LEAD', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (190, 'Submit White Paper', 'Submit White Paper', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 13, 'SUBMIT_WHITE_PAPER', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (191, 'Reconcile NSTL Data', 'Reconcile NSTL Data', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 18, 'RECOMCILE_NSTL_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (192, 'Manage Sales Leads', 'Manage Sales Leads', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 5, 'MANAGE_SALES_LEADS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (193, 'Manage White Papers', 'Manage White Papers', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 6, 'MANAGE_WHITE_PAPERS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (194, 'Manage FAQs', 'Manage FAQs', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 33, 'MANAGE_FAQS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (195, 'Manage Topics', 'Manage Topics', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 34, 'MANAGE_TOPICS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (196, 'Staff Performance Report', 'Staff Performance Report', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 39, 'STAFF_PERFORMANCE_REPORT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (197, 'Web Site Stats', 'Web Site Stats', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 40, 'WEBSITE_STATS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (198, 'GIN Report - Certified Apps', 'GIN Report - Certified Apps', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 41, 'GIN_REP_CERT_APPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (199, 'GIN Report - Accepted Apps', 'GIN Report - Accepted Apps', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 42, 'GIN_REP_ACCEPTED_APPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (200, 'Brew Evaluation Information', 'Brew Evaluation Information', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'BREW_EVALUATION_INFO', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (201, 'GIN Report - Apps Under Testing', 'GIN Report - Apps Under Testing', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 43, 'GIN_REP_APPS_UNDER_TESTING', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (202, 'GIN Report - Live GIN', 'GIN Report - Live GIN', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 44, 'GIN_REP_LIVE_GIN', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (203, 'GIN Report - GIN History', 'GIN Report - GIN History', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 45, 'GIN_REP_GIN_HISTORY', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (210, 'Industry Focus', 'Industry Focus', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 55, 'INDUSTRY_FOCUS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (211, 'Programming Languages', 'Programming Languages', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 'PROGRAMMING_LANGUAGES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (212, 'Browsers', 'Browsers', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 57, 'BROWSERS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (213, 'VZW Platforms', 'VZW Platforms', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 58, 'VZW_PLATFORMS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (214, 'Features', 'Features', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 59, 'FEATURES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (215, 'Lines of Business', 'Lines of Business', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 60, 'LINES_OF_BUSINESS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (216, 'Certifications', 'Certifications', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 15, 'CERTIFICATIONS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (217, 'Manage Dicussion Forum', 'Manage Dicussion Forum', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 30, 'MANAGE_FORUM', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (218, 'Live Chat', 'Live Chat', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 27, 'LIVE_CHAT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (219, 'Manage Chat Sessions', 'Manage Chat Sessions', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 28, 'MANAGE_CHAT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (220, 'Decks', 'Decks', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 71, 'DECKS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (221, 'Manage Users', 'Manage Users', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'systenm', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 14, 'ALLIANCE_USERS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (250, 'Application Evaluation Form', 'Application Evaluation Form', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'APP_EVALUATION_FORM', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (251, 'Reconcile Catalog Data', 'Reconcile Catalog Data', 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 20, 'RECONCILE_CATALOG_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (252, 'Upload Catalog Data', 'Upload Catalog Data', 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 19, 'UPLOAD_CATALOG_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (253, 'Manage FAQ Categories', 'Manage FAQ Categories', 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 72, 'MANAGE_FAQ_CATEGORIES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (254, 'Manage Notifications', 'Manage Notifications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 11, 73, 'MANAGE_NOTIFICATIONS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (255, 'New BREW Applications', 'New BREW Applications', 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 74, 'NEW_BREW_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (256, 'New Enterprise Applications', 'New Enterprise Applications', 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 75, 'NEW_ENTERPRISE_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (257, 'New MMS Applications', 'New MMS Applications', 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 76, 'NEW_MMS_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (258, 'New SMS Applications', 'New SMS Applications', 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 77, 'NEW_SMS_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (259, 'New WAP Applications', 'New WAP Applications', 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/19/2004 21:23:09', 'MM/DD/YYYY HH24:MI:SS'), 78, 'NEW_WAP_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (260, 'New BREW Concepts', 'New BREW Concepts', 'system', TO_DATE('07/27/2004 18:21:01', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('07/27/2004 18:21:01', 'MM/DD/YYYY HH24:MI:SS'), 80, 'NEW_BREW_CONCEPTS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (261, 'Search Program Guide', 'Search Program Guide', 'system', TO_DATE('08/30/2004 12:07:29', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('08/30/2004 12:07:29', 'MM/DD/YYYY HH24:MI:SS'), 81, 'SEARCH_PROGRAM_GUIDE', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (262, 'Provisioned Apps', 'Provisioned Apps', 'system', TO_DATE('09/03/2004 14:45:42', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/03/2004 14:45:42', 'MM/DD/YYYY HH24:MI:SS'), 16, 'PROVISIONED_APPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (263, 'Manage Provisioned Apps', 'Manage Provisioned Apps', 'system', TO_DATE('09/09/2004 16:21:20', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/09/2004 16:21:20', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_PROV_APPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (264, 'Manage Initial Approval Section in Wap Application''s Processing Information Page', 'Manage Initial Approval Section in Wap Application''s Processing Information Page', 'system', TO_DATE('09/21/2004 17:33:04', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/21/2004 17:33:04', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_INITIAL_APPROVAL', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (265, 'Manage Initial Buisness Approval Section in Wap Application''s Processing Information Page', 'Manage Initial Business Approval Section in Wap Application''s Processing Information Page', 'system', TO_DATE('09/21/2004 17:34:19', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/21/2004 17:34:19', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_INITIAL_BUSINESS_APPROVAL', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (266, 'Manage Move to Pending DCR  Section in Wap Application''s Processing Information Page', 'Manage Move to Pending DCR Section in Wap Application''s Processing Information Page', 'system', TO_DATE('09/23/2004 14:40:06', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/23/2004 14:40:06', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_MOVE_TO_PENDING_DCR', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (267, 'Manage Pending DCR  Section in Wap Application''s Processing Information Page', 'Manage Pending DCR Section in Wap Application''s Processing Information Page', 'system', TO_DATE('09/27/2004 17:19:21', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/27/2004 17:19:21', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_PENDING_DCR', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (268, 'Manage Content Testing Section in Wap Application''s Processing Information Page', 'Manage Content Testing Section in Wap Application''s Processing Information Page', 'system', TO_DATE('10/05/2004 17:17:53', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/05/2004 17:17:53', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_CONTENT_TESTING', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (269, 'Manage Content Completion Section in Wap Application''s Processing Information Page', 'Manage Content Completion Section in Wap Application''s Processing Information Page', 'system', TO_DATE('10/08/2004 12:30:23', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/08/2004 12:30:23', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_CONTENT_COMPLETION', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (270, 'Manage Content Removal Section in Wap Application''s Processing Information Page', 'Manage Content Removal Section in Wap Application''s Processing Information Page', 'system', TO_DATE('10/07/2004 18:39:10', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/07/2004 18:39:10', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_CONTENT_REMOVAL', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (271, 'Marketing User Module', 'Marketing User Module', 19, 'MARKETING_CONTENT_MODULE', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (272, 'Marketing Applications List', 'Marketing Applications List', 90, 'MARKETING_APP_LIST', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (273, 'Marketing Search Applications', 'Marketing Search Applications', 91, 'MARKETING_SEARCH_APP', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (274, 'Marketing Provisioned Applications', 'Marketing Provisioned Applications', 92, 'MARKETING_PROV_APP', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (275, 'Marketing Manage Content Requests', 'Marketing Manage Content Requests', 93, 'MARKETING_MANAGE_CONTENT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (276, 'Marketing VZW Administrator Content Request', 'Marketing content requests module for handling approvals of creative requests', 17, 'MARKETING_ADMIN_CONTENT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (277, 'Marketing Alliance Content Request', 'Interface for accepting application requested for creative contents', 18, 'MARKETING_ALLIANCE_CONTENT', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (278, 'Create Application', 'Create Application', 'system', TO_DATE('11/24/2004 17:38:58', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('11/24/2004 17:38:58', 'MM/DD/YYYY HH24:MI:SS'), 82, 'CREATE_APPLICATION', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (279, 'Manage VCAST Apps', 'Manage VCAST Apps', 'system', TO_DATE('03/25/2005 22:06:30', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/25/2005 22:06:30', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_VCAST', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (280, 'Marketing Content', 'Content Request', 94, 'MARKETING_CONTENT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (281, 'Provisioned Content', 'Provisioned Content', 95, 'NEW_PROVISIONED_CONTENTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (282, 'Manage Marketing Content', 'Manage Marketing Content', 'system', TO_DATE('04/05/2005 18:22:51', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('04/05/2005 18:22:51', 'MM/DD/YYYY HH24:MI:SS'), 83, 'CP_MARKETING_CONTENT', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (283, 'Submit Marketing Content', 'Submit Marketing Content', 'system', TO_DATE('04/05/2005 18:22:51', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('04/05/2005 18:22:51', 'MM/DD/YYYY HH24:MI:SS'), 84, 'SUBMIT_MARKETING_CONTENT', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (503, 'Review Content Request', 'Review Content Request', 98, 'REVIEW_CONTENT_REQUEST', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (504, 'Applications For Legal Review', 'Applications For Legal Review', 'system', TO_DATE('11/23/2005 06:26:58', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('11/23/2005 06:26:58', 'MM/DD/YYYY HH24:MI:SS'), 100, 'APPLICATIONS_FOR_LEGAL_REVIEW', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (505, 'Upload Device on Loan Data', 'Upload Device on Loan Data', 'system', TO_DATE('01/30/2006 07:27:05', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('01/30/2006 07:27:05', 'MM/DD/YYYY HH24:MI:SS'), 101, 'UPLOAD_DEVICE_ON_LOAN_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (510, 'Manage Wap Application''s rollback to Pending DCR status', 'Manage Wap Application''s rollback to Pending DCR status', 'system', TO_DATE('05/04/2006 20:20:50', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/04/2006 20:20:50', 'MM/DD/YYYY HH24:MI:SS'), 102, 'WAP_APP_ROLLBACK_TO_PENDING_DCR', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (520, 'VCAST Music Information', 'VCAST Music', 'system', TO_DATE('07/05/2006 13:00:51', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('07/05/2006 13:00:51', 'MM/DD/YYYY HH24:MI:SS'), 110, 'VCAST_MUSIC_INFORMATION', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (525, 'All VCAST Music Alliances', 'All VCAST Music Alliances', 'system', TO_DATE('07/05/2006 13:00:51', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('07/05/2006 13:00:51', 'MM/DD/YYYY HH24:MI:SS'), 115, 'ALL_MUSIC_ALLIANCES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (530, 'Change Alliance Administrator', 'Change Alliance Administrator', 'system', TO_DATE('09/14/2006 19:50:30', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/14/2006 19:50:30', 'MM/DD/YYYY HH24:MI:SS'), 22, 'CHANGE_ALLIANCE_ADMIN', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (531, 'Wap FTP Manual', 'Wap FTP Manual', 'system', TO_DATE('10/05/2007 19:12:20', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/05/2007 19:12:20', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_FTP_IMAGE_MANUAL', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (532, 'Upload WAP Icons', 'Upload WAP Icons', 'system', TO_DATE('10/05/2007 19:12:20', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/05/2007 19:12:20', 'MM/DD/YYYY HH24:MI:SS'), 116, 'UPLOAD_WAP_ICONS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (533, 'Export Content Filter URLs', 'Export Content Filter URLs', 'system', TO_DATE('10/25/2007 13:22:39', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/25/2007 13:22:39', 'MM/DD/YYYY HH24:MI:SS'), 'EXPORT_CONTENT_FILTER_URLS', 'B');


