//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfferPackagingOptionsDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfferPackagingOptionsDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offerPackagingType" type="{http://api.qpass.com/productoffer}OfferPackagingOptionsEnumType"/>
 *         &lt;element name="maxAccessCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="validityPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="overageAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="overageCharge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfferPackagingOptionsDataType", propOrder = {
    "offerPackagingType",
    "maxAccessCount",
    "validityPeriod",
    "overageAllowed",
    "overageCharge"
})
public class OfferPackagingOptionsDataType {

    @XmlElement(required = true)
    protected OfferPackagingOptionsEnumType offerPackagingType;
    protected String maxAccessCount;
    protected String validityPeriod;
    @XmlElement(defaultValue = "false")
    protected Boolean overageAllowed;
    protected String overageCharge;

    /**
     * Gets the value of the offerPackagingType property.
     * 
     * @return
     *     possible object is
     *     {@link OfferPackagingOptionsEnumType }
     *     
     */
    public OfferPackagingOptionsEnumType getOfferPackagingType() {
        return offerPackagingType;
    }

    /**
     * Sets the value of the offerPackagingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferPackagingOptionsEnumType }
     *     
     */
    public void setOfferPackagingType(OfferPackagingOptionsEnumType value) {
        this.offerPackagingType = value;
    }

    /**
     * Gets the value of the maxAccessCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxAccessCount() {
        return maxAccessCount;
    }

    /**
     * Sets the value of the maxAccessCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxAccessCount(String value) {
        this.maxAccessCount = value;
    }

    /**
     * Gets the value of the validityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityPeriod() {
        return validityPeriod;
    }

    /**
     * Sets the value of the validityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityPeriod(String value) {
        this.validityPeriod = value;
    }

    /**
     * Gets the value of the overageAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOverageAllowed() {
        return overageAllowed;
    }

    /**
     * Sets the value of the overageAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOverageAllowed(Boolean value) {
        this.overageAllowed = value;
    }

    /**
     * Gets the value of the overageCharge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverageCharge() {
        return overageCharge;
    }

    /**
     * Sets the value of the overageCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverageCharge(String value) {
        this.overageCharge = value;
    }

}
