//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfferPricingMethodsEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OfferPricingMethodsEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pos"/>
 *     &lt;enumeration value="standard"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OfferPricingMethodsEnumType")
@XmlEnum
public enum OfferPricingMethodsEnumType {

    @XmlEnumValue("pos")
    POS("pos"),
    @XmlEnumValue("standard")
    STANDARD("standard");
    private final String value;

    OfferPricingMethodsEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OfferPricingMethodsEnumType fromValue(String v) {
        for (OfferPricingMethodsEnumType c: OfferPricingMethodsEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
