//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfferChargeFrequencyEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OfferChargeFrequencyEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="oneTime"/>
 *     &lt;enumeration value="recurring"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OfferChargeFrequencyEnumType")
@XmlEnum
public enum OfferChargeFrequencyEnumType {

    @XmlEnumValue("oneTime")
    ONE_TIME("oneTime"),
    @XmlEnumValue("recurring")
    RECURRING("recurring");
    private final String value;

    OfferChargeFrequencyEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OfferChargeFrequencyEnumType fromValue(String v) {
        for (OfferChargeFrequencyEnumType c: OfferChargeFrequencyEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
