//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductOfferTermDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductOfferTermDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="offerDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="offerCategoryData" type="{http://api.qpass.com/productoffer}OfferCategoryEnumDataType"/>
 *         &lt;element name="taxSchemaData" type="{http://api.qpass.com/productoffer}TaxSchemaDataType"/>
 *         &lt;element name="offerExpiration" type="{http://api.qpass.com/productoffer}OfferExpirationEnumType"/>
 *         &lt;element name="offerExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="priceSchemeData" type="{http://api.qpass.com/productoffer}PriceSchemeDataType"/>
 *         &lt;element name="paymentPlanData" type="{http://api.qpass.com/productoffer}PaymentPlanDataType"/>
 *         &lt;element name="requirementData" type="{http://api.qpass.com/productoffer}RequirementDataType"/>
 *         &lt;element name="compositionData" type="{http://api.qpass.com/productoffer}CompositionDataType"/>
 *         &lt;element name="countedAccessOfferTermsData" type="{http://api.qpass.com/productoffer}OfferPackagingOptionsDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductOfferTermDataType", propOrder = {
    "offerName",
    "offerDescription",
    "offerCategoryData",
    "taxSchemaData",
    "offerExpiration",
    "offerExpirationDate",
    "priceSchemeData",
    "paymentPlanData",
    "requirementData",
    "compositionData",
    "countedAccessOfferTermsData"
})
public class ProductOfferTermDataType {

    @XmlElement(required = true)
    protected String offerName;
    @XmlElement(required = true)
    protected String offerDescription;
    @XmlElement(required = true)
    protected OfferCategoryEnumDataType offerCategoryData;
    @XmlElement(required = true)
    protected TaxSchemaDataType taxSchemaData;
    @XmlElement(required = true)
    protected OfferExpirationEnumType offerExpiration;
    protected String offerExpirationDate;
    @XmlElement(required = true)
    protected PriceSchemeDataType priceSchemeData;
    @XmlElement(required = true)
    protected PaymentPlanDataType paymentPlanData;
    @XmlElement(required = true)
    protected RequirementDataType requirementData;
    @XmlElement(required = true)
    protected CompositionDataType compositionData;
    protected OfferPackagingOptionsDataType countedAccessOfferTermsData;

    /**
     * Gets the value of the offerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferName() {
        return offerName;
    }

    /**
     * Sets the value of the offerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferName(String value) {
        this.offerName = value;
    }

    /**
     * Gets the value of the offerDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferDescription() {
        return offerDescription;
    }

    /**
     * Sets the value of the offerDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferDescription(String value) {
        this.offerDescription = value;
    }

    /**
     * Gets the value of the offerCategoryData property.
     * 
     * @return
     *     possible object is
     *     {@link OfferCategoryEnumDataType }
     *     
     */
    public OfferCategoryEnumDataType getOfferCategoryData() {
        return offerCategoryData;
    }

    /**
     * Sets the value of the offerCategoryData property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferCategoryEnumDataType }
     *     
     */
    public void setOfferCategoryData(OfferCategoryEnumDataType value) {
        this.offerCategoryData = value;
    }

    /**
     * Gets the value of the taxSchemaData property.
     * 
     * @return
     *     possible object is
     *     {@link TaxSchemaDataType }
     *     
     */
    public TaxSchemaDataType getTaxSchemaData() {
        return taxSchemaData;
    }

    /**
     * Sets the value of the taxSchemaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxSchemaDataType }
     *     
     */
    public void setTaxSchemaData(TaxSchemaDataType value) {
        this.taxSchemaData = value;
    }

    /**
     * Gets the value of the offerExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link OfferExpirationEnumType }
     *     
     */
    public OfferExpirationEnumType getOfferExpiration() {
        return offerExpiration;
    }

    /**
     * Sets the value of the offerExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferExpirationEnumType }
     *     
     */
    public void setOfferExpiration(OfferExpirationEnumType value) {
        this.offerExpiration = value;
    }

    /**
     * Gets the value of the offerExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferExpirationDate() {
        return offerExpirationDate;
    }

    /**
     * Sets the value of the offerExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferExpirationDate(String value) {
        this.offerExpirationDate = value;
    }

    /**
     * Gets the value of the priceSchemeData property.
     * 
     * @return
     *     possible object is
     *     {@link PriceSchemeDataType }
     *     
     */
    public PriceSchemeDataType getPriceSchemeData() {
        return priceSchemeData;
    }

    /**
     * Sets the value of the priceSchemeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceSchemeDataType }
     *     
     */
    public void setPriceSchemeData(PriceSchemeDataType value) {
        this.priceSchemeData = value;
    }

    /**
     * Gets the value of the paymentPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentPlanDataType }
     *     
     */
    public PaymentPlanDataType getPaymentPlanData() {
        return paymentPlanData;
    }

    /**
     * Sets the value of the paymentPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentPlanDataType }
     *     
     */
    public void setPaymentPlanData(PaymentPlanDataType value) {
        this.paymentPlanData = value;
    }

    /**
     * Gets the value of the requirementData property.
     * 
     * @return
     *     possible object is
     *     {@link RequirementDataType }
     *     
     */
    public RequirementDataType getRequirementData() {
        return requirementData;
    }

    /**
     * Sets the value of the requirementData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequirementDataType }
     *     
     */
    public void setRequirementData(RequirementDataType value) {
        this.requirementData = value;
    }

    /**
     * Gets the value of the compositionData property.
     * 
     * @return
     *     possible object is
     *     {@link CompositionDataType }
     *     
     */
    public CompositionDataType getCompositionData() {
        return compositionData;
    }

    /**
     * Sets the value of the compositionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositionDataType }
     *     
     */
    public void setCompositionData(CompositionDataType value) {
        this.compositionData = value;
    }

    /**
     * Gets the value of the countedAccessOfferTermsData property.
     * 
     * @return
     *     possible object is
     *     {@link OfferPackagingOptionsDataType }
     *     
     */
    public OfferPackagingOptionsDataType getCountedAccessOfferTermsData() {
        return countedAccessOfferTermsData;
    }

    /**
     * Sets the value of the countedAccessOfferTermsData property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferPackagingOptionsDataType }
     *     
     */
    public void setCountedAccessOfferTermsData(OfferPackagingOptionsDataType value) {
        this.countedAccessOfferTermsData = value;
    }

}
