//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxNexusPreferenceEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TaxNexusPreferenceEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CONTENT_PROVIDER"/>
 *     &lt;enumeration value="NETWORK_OPERATOR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TaxNexusPreferenceEnumType")
@XmlEnum
public enum TaxNexusPreferenceEnumType {

    CONTENT_PROVIDER,
    NETWORK_OPERATOR;

    public String value() {
        return name();
    }

    public static TaxNexusPreferenceEnumType fromValue(String v) {
        return valueOf(v);
    }

}
