CREATE DATABASE /*!32312 IF NOT EXISTS*/`vzdnBlog_audit` /*!40100*/ DEFAULT CHARACTER SET utf8 ;

GRANT ALL ON vzdnBlog.* TO 'vzdnBlog_audit'@'%' IDENTIFIED BY 'vzdnBlog_audit';

USE vzdnBlog_audit;

CREATE TABLE autoping$aud ENGINE = INNODB AS SELECT id,websiteid,pingtargetid,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.autoping WHERE 1 = 0;	
CREATE TABLE bookmark$aud ENGINE = INNODB AS SELECT id,folderid,name,description,url,weight,priority,image,feedurl,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.bookmark WHERE 1 = 0;	
CREATE TABLE entryattribute$aud ENGINE = INNODB AS SELECT id,entryid,name,value,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.entryattribute WHERE 1 = 0;	
CREATE TABLE folder$aud ENGINE = INNODB AS SELECT id,name,description,websiteid,parentid,path,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.folder WHERE 1 = 0;	
CREATE TABLE folderassoc$aud ENGINE = INNODB AS SELECT id,folderid,ancestorid,relation,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.folderassoc WHERE 1 = 0;	
CREATE TABLE newsfeed$aud ENGINE = INNODB AS SELECT id,name,description,link,websiteid,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.newsfeed WHERE 1 = 0;	
CREATE TABLE pingcategory$aud ENGINE = INNODB AS SELECT id,autopingid,categoryid,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.pingcategory WHERE 1 = 0;	
CREATE TABLE pingqueueentry$aud ENGINE = INNODB AS SELECT id,entrytime,pingtargetid,websiteid,attempts,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.pingqueueentry WHERE 1 = 0;	
CREATE TABLE pingtarget$aud ENGINE = INNODB AS SELECT id,name,pingurl,websiteid,conditioncode,lastsuccess,autoenabled,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.pingtarget WHERE 1 = 0;	
CREATE TABLE rag_entry$aud ENGINE = INNODB AS SELECT id,subscription_id,handle,title,guid,permalink,author,content,categories,published,updated,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.rag_entry WHERE 1 = 0;	
CREATE TABLE rag_group$aud ENGINE = INNODB AS SELECT id,planet_id,handle,title,description,max_page_entries,max_feed_entries,cat_restriction,group_page,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.rag_group WHERE 1 = 0;	
CREATE TABLE rag_group_subscription$aud ENGINE = INNODB AS SELECT group_id,subscription_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.rag_group_subscription WHERE 1 = 0;	
CREATE TABLE rag_planet$aud ENGINE = INNODB AS SELECT id,handle,title,description,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.rag_planet WHERE 1 = 0;	
CREATE TABLE rag_properties$aud ENGINE = INNODB AS SELECT name,value,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.rag_properties WHERE 1 = 0;	
CREATE TABLE rag_subscription$aud ENGINE = INNODB AS SELECT id,title,feed_url,site_url,author,last_updated,inbound_links,inbound_blogs,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.rag_subscription WHERE 1 = 0;	
CREATE TABLE referer$aud ENGINE = INNODB AS SELECT id,websiteid,entryid,datestr,refurl,refpermalink,reftime,requrl,title,excerpt,dayhits,totalhits,visible,duplicate,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.referer WHERE 1 = 0;	
CREATE TABLE roller_audit_log$aud ENGINE = INNODB AS SELECT id,user_id,object_id,object_class,comment_text,change_time,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.roller_audit_log WHERE 1 = 0;	
CREATE TABLE roller_comment$aud ENGINE = INNODB AS SELECT id,entryid,name,email,url,content,posttime,notify,remotehost,referrer,useragent,status,plugins,contenttype,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.roller_comment WHERE 1 = 0;	
CREATE TABLE roller_hitcounts$aud ENGINE = INNODB AS SELECT id,websiteid,dailyhits,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.roller_hitcounts WHERE 1 = 0;	
CREATE TABLE roller_properties$aud ENGINE = INNODB AS SELECT name,value,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.roller_properties WHERE 1 = 0;	
CREATE TABLE roller_tasklock$aud ENGINE = INNODB AS SELECT id,name,islocked,timeacquired,timeleased,lastrun,client,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.roller_tasklock WHERE 1 = 0;	
CREATE TABLE roller_user_permissions$aud ENGINE = INNODB AS SELECT id,website_id,user_id,permission_mask,pending,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.roller_user_permissions WHERE 1 = 0;	
CREATE TABLE roller_weblogentrytag$aud ENGINE = INNODB AS SELECT id,entryid,websiteid,userid,name,time,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.roller_weblogentrytag WHERE 1 = 0;	
CREATE TABLE roller_weblogentrytagagg$aud ENGINE = INNODB AS SELECT id,websiteid,name,total,lastused,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.roller_weblogentrytagagg WHERE 1 = 0;	
CREATE TABLE rollerconfig$aud ENGINE = INNODB AS SELECT id,sitedescription,sitename,emailaddress,absoluteurl,adminusers,encryptpasswords,algorithm,newuserallowed,editorpages,userthemes,indexdir,memdebug,autoformatcomments,escapecommenthtml,emailcomments,enableaggregator,enablelinkback,rsscachetime,rssusecache,uploadallow,uploadforbid,uploadenabled,uploaddir,uploadpath,uploadmaxdirmb,uploadmaxfilemb,dbversion,refspamwords,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.rollerconfig WHERE 1 = 0;	
CREATE TABLE rolleruser$aud ENGINE = INNODB AS SELECT id,username,passphrase,screenname,fullname,emailaddress,activationcode,datecreated,locale,timezone,isenabled,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.rolleruser WHERE 1 = 0;	
CREATE TABLE usercookie$aud ENGINE = INNODB AS SELECT id,username,cookieid,datecreated,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.usercookie WHERE 1 = 0;	
CREATE TABLE userrole$aud ENGINE = INNODB AS SELECT id,rolename,username,userid,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.userrole WHERE 1 = 0;	
CREATE TABLE weblogcategory$aud ENGINE = INNODB AS SELECT id,name,description,websiteid,image,parentid,path,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.weblogcategory WHERE 1 = 0;	
CREATE TABLE weblogcategoryassoc$aud ENGINE = INNODB AS SELECT id,categoryid,ancestorid,relation,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.weblogcategoryassoc WHERE 1 = 0;	
CREATE TABLE weblogentry$aud ENGINE = INNODB AS SELECT id,userid,anchor,title,text,pubtime,updatetime,websiteid,categoryid,publishentry,link,plugins,allowcomments,commentdays,rightToLeft,pinnedtomain,locale,status,summary,content_type,content_src,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.weblogentry WHERE 1 = 0;	
CREATE TABLE webpage$aud ENGINE = INNODB AS SELECT id,name,description,link,websiteid,template,updatetime,hidden,navbar,templatelang,decorator,outputtype,action,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.webpage WHERE 1 = 0;	
CREATE TABLE website$aud ENGINE = INNODB AS SELECT id,name,handle,description,userid,defaultpageid,weblogdayid,ignorewords,enablebloggerapi,editorpage,bloggercatid,defaultcatid,allowcomments,emailcomments,emailfromaddress,emailaddress,editortheme,locale,timezone,defaultplugins,isenabled,isactive,datecreated,blacklist,defaultallowcomments,defaultcommentdays,commentmod,displaycnt,lastmodified,pagemodels,enablemultilang,showalllangs,customstylesheet,about,icon,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdnBlog.website WHERE 1 = 0;	

GRANT ALL ON vzdnBlog_audit.* TO 'vzdnBlog'@'%' IDENTIFIED BY 'vzdnBlog';
GRANT ALL ON vzdnBlog.* TO 'vzdnBlog'@'%' IDENTIFIED BY 'vzdnBlog';
