
package com.ttdev.service.img;

import javax.xml.ws.Endpoint;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-23T14:49:54.399-08:00
 * Generated source version: 2.7.8
 * 
 */
 
public class ImageService_P1_Server{

    protected ImageService_P1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ImageServiceImpl();
        String address = "http://localhost:8080/is/p1";
        Endpoint endpoint=Endpoint.publish(address, implementor);
        SOAPBinding soapBinding = (SOAPBinding)endpoint.getBinding();
        soapBinding.setMTOMEnabled(true);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ImageService_P1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
