//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConstraintDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConstraintDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accessPeriodOption" type="{http://api.qpass.com/productoffer}OfferAccessPeriodOptionsEnumType"/>
 *         &lt;element name="reaccessWithinTimeCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reaccessWithinTimeUnit" type="{http://api.qpass.com/productoffer}OfferReaccessWithinEnumType" minOccurs="0"/>
 *         &lt;element name="reaccessUntil" type="{http://api.qpass.com/productoffer}OfferReaccessUntilEnumType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConstraintDataType", propOrder = {
    "accessPeriodOption",
    "reaccessWithinTimeCount",
    "reaccessWithinTimeUnit",
    "reaccessUntil"
})
public class ConstraintDataType {

    @XmlElement(required = true)
    protected OfferAccessPeriodOptionsEnumType accessPeriodOption;
    protected String reaccessWithinTimeCount;
    protected OfferReaccessWithinEnumType reaccessWithinTimeUnit;
    protected OfferReaccessUntilEnumType reaccessUntil;

    /**
     * Gets the value of the accessPeriodOption property.
     * 
     * @return
     *     possible object is
     *     {@link OfferAccessPeriodOptionsEnumType }
     *     
     */
    public OfferAccessPeriodOptionsEnumType getAccessPeriodOption() {
        return accessPeriodOption;
    }

    /**
     * Sets the value of the accessPeriodOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferAccessPeriodOptionsEnumType }
     *     
     */
    public void setAccessPeriodOption(OfferAccessPeriodOptionsEnumType value) {
        this.accessPeriodOption = value;
    }

    /**
     * Gets the value of the reaccessWithinTimeCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReaccessWithinTimeCount() {
        return reaccessWithinTimeCount;
    }

    /**
     * Sets the value of the reaccessWithinTimeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReaccessWithinTimeCount(String value) {
        this.reaccessWithinTimeCount = value;
    }

    /**
     * Gets the value of the reaccessWithinTimeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link OfferReaccessWithinEnumType }
     *     
     */
    public OfferReaccessWithinEnumType getReaccessWithinTimeUnit() {
        return reaccessWithinTimeUnit;
    }

    /**
     * Sets the value of the reaccessWithinTimeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferReaccessWithinEnumType }
     *     
     */
    public void setReaccessWithinTimeUnit(OfferReaccessWithinEnumType value) {
        this.reaccessWithinTimeUnit = value;
    }

    /**
     * Gets the value of the reaccessUntil property.
     * 
     * @return
     *     possible object is
     *     {@link OfferReaccessUntilEnumType }
     *     
     */
    public OfferReaccessUntilEnumType getReaccessUntil() {
        return reaccessUntil;
    }

    /**
     * Sets the value of the reaccessUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferReaccessUntilEnumType }
     *     
     */
    public void setReaccessUntil(OfferReaccessUntilEnumType value) {
        this.reaccessUntil = value;
    }

}
