//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfferExpirationEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OfferExpirationEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="retires"/>
 *     &lt;enumeration value="neverRetires"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OfferExpirationEnumType")
@XmlEnum
public enum OfferExpirationEnumType {

    @XmlEnumValue("retires")
    RETIRES("retires"),
    @XmlEnumValue("neverRetires")
    NEVER_RETIRES("neverRetires");
    private final String value;

    OfferExpirationEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OfferExpirationEnumType fromValue(String v) {
        for (OfferExpirationEnumType c: OfferExpirationEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
