//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfferPackagingOptionsEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OfferPackagingOptionsEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="item"/>
 *     &lt;enumeration value="instance"/>
 *     &lt;enumeration value="countedAccess"/>
 *     &lt;enumeration value="bundleAccess"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OfferPackagingOptionsEnumType")
@XmlEnum
public enum OfferPackagingOptionsEnumType {

    @XmlEnumValue("item")
    ITEM("item"),
    @XmlEnumValue("instance")
    INSTANCE("instance"),
    @XmlEnumValue("countedAccess")
    COUNTED_ACCESS("countedAccess"),
    @XmlEnumValue("bundleAccess")
    BUNDLE_ACCESS("bundleAccess");
    private final String value;

    OfferPackagingOptionsEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OfferPackagingOptionsEnumType fromValue(String v) {
        for (OfferPackagingOptionsEnumType c: OfferPackagingOptionsEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
