//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfferAccessPeriodOptionsEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OfferAccessPeriodOptionsEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="free"/>
 *     &lt;enumeration value="expires"/>
 *     &lt;enumeration value="within"/>
 *     &lt;enumeration value="until"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OfferAccessPeriodOptionsEnumType")
@XmlEnum
public enum OfferAccessPeriodOptionsEnumType {

    @XmlEnumValue("free")
    FREE("free"),
    @XmlEnumValue("expires")
    EXPIRES("expires"),
    @XmlEnumValue("within")
    WITHIN("within"),
    @XmlEnumValue("until")
    UNTIL("until");
    private final String value;

    OfferAccessPeriodOptionsEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OfferAccessPeriodOptionsEnumType fromValue(String v) {
        for (OfferAccessPeriodOptionsEnumType c: OfferAccessPeriodOptionsEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
