//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentPlanDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentPlanDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chargeFrequency" type="{http://api.qpass.com/productoffer}OfferChargeFrequencyEnumType"/>
 *         &lt;element name="periodicityInterval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="periodicityUnit" type="{http://api.qpass.com/productoffer}OfferChagePeriodicityUnitsEnumType" minOccurs="0"/>
 *         &lt;element name="billingDelay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recurringChargePeriodInterval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentPlanDataType", propOrder = {
    "chargeFrequency",
    "periodicityInterval",
    "periodicityUnit",
    "billingDelay",
    "recurringChargePeriodInterval"
})
public class PaymentPlanDataType {

    @XmlElement(required = true)
    protected OfferChargeFrequencyEnumType chargeFrequency;
    protected String periodicityInterval;
    protected OfferChagePeriodicityUnitsEnumType periodicityUnit;
    protected String billingDelay;
    protected String recurringChargePeriodInterval;

    /**
     * Gets the value of the chargeFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link OfferChargeFrequencyEnumType }
     *     
     */
    public OfferChargeFrequencyEnumType getChargeFrequency() {
        return chargeFrequency;
    }

    /**
     * Sets the value of the chargeFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferChargeFrequencyEnumType }
     *     
     */
    public void setChargeFrequency(OfferChargeFrequencyEnumType value) {
        this.chargeFrequency = value;
    }

    /**
     * Gets the value of the periodicityInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicityInterval() {
        return periodicityInterval;
    }

    /**
     * Sets the value of the periodicityInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicityInterval(String value) {
        this.periodicityInterval = value;
    }

    /**
     * Gets the value of the periodicityUnit property.
     * 
     * @return
     *     possible object is
     *     {@link OfferChagePeriodicityUnitsEnumType }
     *     
     */
    public OfferChagePeriodicityUnitsEnumType getPeriodicityUnit() {
        return periodicityUnit;
    }

    /**
     * Sets the value of the periodicityUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferChagePeriodicityUnitsEnumType }
     *     
     */
    public void setPeriodicityUnit(OfferChagePeriodicityUnitsEnumType value) {
        this.periodicityUnit = value;
    }

    /**
     * Gets the value of the billingDelay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingDelay() {
        return billingDelay;
    }

    /**
     * Sets the value of the billingDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingDelay(String value) {
        this.billingDelay = value;
    }

    /**
     * Gets the value of the recurringChargePeriodInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecurringChargePeriodInterval() {
        return recurringChargePeriodInterval;
    }

    /**
     * Sets the value of the recurringChargePeriodInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecurringChargePeriodInterval(String value) {
        this.recurringChargePeriodInterval = value;
    }

}
