//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriceSchemeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceSchemeDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offerPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="offerPricingMethod" type="{http://api.qpass.com/productoffer}OfferPricingMethodsEnumType"/>
 *         &lt;element name="offerPriceAdjustable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceSchemeDataType", propOrder = {
    "offerPrice",
    "offerPricingMethod",
    "offerPriceAdjustable"
})
public class PriceSchemeDataType {

    @XmlElement(required = true)
    protected String offerPrice;
    @XmlElement(required = true)
    protected OfferPricingMethodsEnumType offerPricingMethod;
    @XmlElement(defaultValue = "false")
    protected Boolean offerPriceAdjustable;

    /**
     * Gets the value of the offerPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferPrice() {
        return offerPrice;
    }

    /**
     * Sets the value of the offerPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferPrice(String value) {
        this.offerPrice = value;
    }

    /**
     * Gets the value of the offerPricingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link OfferPricingMethodsEnumType }
     *     
     */
    public OfferPricingMethodsEnumType getOfferPricingMethod() {
        return offerPricingMethod;
    }

    /**
     * Sets the value of the offerPricingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferPricingMethodsEnumType }
     *     
     */
    public void setOfferPricingMethod(OfferPricingMethodsEnumType value) {
        this.offerPricingMethod = value;
    }

    /**
     * Gets the value of the offerPriceAdjustable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOfferPriceAdjustable() {
        return offerPriceAdjustable;
    }

    /**
     * Sets the value of the offerPriceAdjustable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOfferPriceAdjustable(Boolean value) {
        this.offerPriceAdjustable = value;
    }

}
