//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			     Complex type representing the root element containing errors and product offer data.
 * 			
 * 
 * <p>Java class for ProductOfferType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductOfferType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errors" type="{http://api.qpass.com/productoffer}ErrorsType" minOccurs="0"/>
 *         &lt;element name="productOfferData" type="{http://api.qpass.com/productoffer}ProductOfferDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name ="ProductOffer", namespace="http://api.qpass.com/productoffer")
@XmlType(name = "ProductOffer", propOrder = {
    "errors",
    "productOfferData"
})
public class ProductOfferType {

    protected ErrorsType errors;
    protected ProductOfferDataType productOfferData;

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorsType }
     *     
     */
    public ErrorsType getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorsType }
     *     
     */
    public void setErrors(ErrorsType value) {
        this.errors = value;
    }

    /**
     * Gets the value of the productOfferData property.
     * 
     * @return
     *     possible object is
     *     {@link ProductOfferDataType }
     *     
     */
    public ProductOfferDataType getProductOfferData() {
        return productOfferData;
    }

    /**
     * Sets the value of the productOfferData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductOfferDataType }
     *     
     */
    public void setProductOfferData(ProductOfferDataType value) {
        this.productOfferData = value;
    }

}
