//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.30 at 12:21:59 PM PKT 
//


package com.netpace.aims.ws.amdocs.offer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductOfferDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductOfferDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vendorWorkingName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productOfferTermData" type="{http://api.qpass.com/productoffer}ProductOfferTermDataType"/>
 *         &lt;element name="approveOffer" type="{http://api.qpass.com/productoffer}approveOfferType" minOccurs="0"/>
 *         &lt;element name="refundable" type="{http://api.qpass.com/productoffer}refundableType" minOccurs="0"/>
 *         &lt;element name="concludable" type="{http://api.qpass.com/productoffer}concludableType" minOccurs="0"/>
 *         &lt;element name="chargesAggregatable" type="{http://api.qpass.com/productoffer}chargesAggregatableType" minOccurs="0"/>
 *         &lt;element name="taxNexusPreference" type="{http://api.qpass.com/productoffer}TaxNexusPreferenceEnumType" minOccurs="0"/>
 *         &lt;element name="contractTemplateId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductOfferDataType", propOrder = {
    "offerId",
    "vendorWorkingName",
    "productOfferTermData",
    "approveOffer",
    "refundable",
    "concludable",
    "chargesAggregatable",
    "taxNexusPreference",
    "contractTemplateId"
})
public class ProductOfferDataType {

    @XmlElement(required = true)
    protected String offerId;
    @XmlElement(required = true)
    protected String vendorWorkingName;
    @XmlElement(required = true)
    protected ProductOfferTermDataType productOfferTermData;
    protected ApproveOfferType approveOffer;
    protected RefundableType refundable;
    protected ConcludableType concludable;
    protected ChargesAggregatableType chargesAggregatable;
    protected TaxNexusPreferenceEnumType taxNexusPreference;
    protected String contractTemplateId;

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferId(String value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the vendorWorkingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorWorkingName() {
        return vendorWorkingName;
    }

    /**
     * Sets the value of the vendorWorkingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorWorkingName(String value) {
        this.vendorWorkingName = value;
    }

    /**
     * Gets the value of the productOfferTermData property.
     * 
     * @return
     *     possible object is
     *     {@link ProductOfferTermDataType }
     *     
     */
    public ProductOfferTermDataType getProductOfferTermData() {
        return productOfferTermData;
    }

    /**
     * Sets the value of the productOfferTermData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductOfferTermDataType }
     *     
     */
    public void setProductOfferTermData(ProductOfferTermDataType value) {
        this.productOfferTermData = value;
    }

    /**
     * Gets the value of the approveOffer property.
     * 
     * @return
     *     possible object is
     *     {@link ApproveOfferType }
     *     
     */
    public ApproveOfferType getApproveOffer() {
        return approveOffer;
    }

    /**
     * Sets the value of the approveOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApproveOfferType }
     *     
     */
    public void setApproveOffer(ApproveOfferType value) {
        this.approveOffer = value;
    }

    /**
     * Gets the value of the refundable property.
     * 
     * @return
     *     possible object is
     *     {@link RefundableType }
     *     
     */
    public RefundableType getRefundable() {
        return refundable;
    }

    /**
     * Sets the value of the refundable property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefundableType }
     *     
     */
    public void setRefundable(RefundableType value) {
        this.refundable = value;
    }

    /**
     * Gets the value of the concludable property.
     * 
     * @return
     *     possible object is
     *     {@link ConcludableType }
     *     
     */
    public ConcludableType getConcludable() {
        return concludable;
    }

    /**
     * Sets the value of the concludable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConcludableType }
     *     
     */
    public void setConcludable(ConcludableType value) {
        this.concludable = value;
    }

    /**
     * Gets the value of the chargesAggregatable property.
     * 
     * @return
     *     possible object is
     *     {@link ChargesAggregatableType }
     *     
     */
    public ChargesAggregatableType getChargesAggregatable() {
        return chargesAggregatable;
    }

    /**
     * Sets the value of the chargesAggregatable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargesAggregatableType }
     *     
     */
    public void setChargesAggregatable(ChargesAggregatableType value) {
        this.chargesAggregatable = value;
    }

    /**
     * Gets the value of the taxNexusPreference property.
     * 
     * @return
     *     possible object is
     *     {@link TaxNexusPreferenceEnumType }
     *     
     */
    public TaxNexusPreferenceEnumType getTaxNexusPreference() {
        return taxNexusPreference;
    }

    /**
     * Sets the value of the taxNexusPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxNexusPreferenceEnumType }
     *     
     */
    public void setTaxNexusPreference(TaxNexusPreferenceEnumType value) {
        this.taxNexusPreference = value;
    }

    /**
     * Gets the value of the contractTemplateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractTemplateId() {
        return contractTemplateId;
    }

    /**
     * Sets the value of the contractTemplateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractTemplateId(String value) {
        this.contractTemplateId = value;
    }

}
