
package com.ch06.ejb.persist.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Fib", targetNamespace = "http://persist.ejb.ch06.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Fib {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fib", targetNamespace = "http://persist.ejb.ch06.com/", className = "com.ch06.ejb.persist.client.Fib_Type")
    @ResponseWrapper(localName = "fibResponse", targetNamespace = "http://persist.ejb.ch06.com/", className = "com.ch06.ejb.persist.client.FibResponse")
    @Action(input = "http://persist.ejb.ch06.com/Fib/fibRequest", output = "http://persist.ejb.ch06.com/Fib/fibResponse")
    public int fib(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFibs", targetNamespace = "http://persist.ejb.ch06.com/", className = "com.ch06.ejb.persist.client.GetFibs")
    @ResponseWrapper(localName = "getFibsResponse", targetNamespace = "http://persist.ejb.ch06.com/", className = "com.ch06.ejb.persist.client.GetFibsResponse")
    @Action(input = "http://persist.ejb.ch06.com/Fib/getFibsRequest", output = "http://persist.ejb.ch06.com/Fib/getFibsResponse")
    public List<Integer> getFibs();

}
