/* Generated by Together */

package com.netpace.vzdn.service.impl;

/**
 * This class works as a factory for EventManager
 * and provides a thread safe implementation of a singleton Eventmanager. 
 */
public class EventManagerFactory
{
    public static EventManager getInstance()
    {
        if (instance == null)
        {
            synchronized(EventManagerFactory.class)
            {
                if (instance == null)
                {
                    instance = new EventManager();
                    instance.loadEvents();
                }
            }
        }
        return instance;
    }

    private static EventManager instance = null;
}
