/* Generated by Together */

package com.netpace.vzdn.service.impl;

import java.util.Enumeration;
import java.util.Hashtable;

import com.netpace.vzdn.model.BaseEvent;
import com.netpace.vzdn.util.StringFuncs;

public class VzdnEventObject
{
    private BaseEvent event = null;
    private String eventName;
    private Hashtable properties;

    public VzdnEventObject(BaseEvent event)
    {
        this.event = event;
        this.properties = new Hashtable();
    }

    public String getEventName()
    {
        return eventName;
    }

    public void setEventName(String eventName)
    {
        this.eventName = eventName;
    }

    public BaseEvent getEvent()
    {
        return event;
    }

    public Object getProperty(String property_name)
    {
        return properties.get(property_name);
    }

    public void setProperty(String property_name, Object property)
    {
        if (property != null)
            properties.put(property_name, property);
    }

    public Hashtable getProperties()
    {
        return properties;
    }

    public Hashtable getPropertiesWithPattern()
    {
        Hashtable propertiesWithPattern = new Hashtable();
        String objKey = null;
        String subsituteStringValue = null;

        for (Enumeration e = properties.keys(); e.hasMoreElements();)
        {
            objKey = (String) e.nextElement();
            subsituteStringValue = properties.get(objKey).toString();
            subsituteStringValue = StringFuncs.string_substitute(subsituteStringValue, ",", "ASC#044");
            subsituteStringValue = StringFuncs.string_substitute(subsituteStringValue, "=", "ASC#061");
            propertiesWithPattern.put("{" + objKey + "}", subsituteStringValue);
        }

        return propertiesWithPattern;
    }
}
