
package com.ch06.teamclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Teams", targetNamespace = "http://ch06.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Teams {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ch06.teamclient.Team
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeam", targetNamespace = "http://ch06.com/", className = "com.ch06.teamclient.GetTeam")
    @ResponseWrapper(localName = "getTeamResponse", targetNamespace = "http://ch06.com/", className = "com.ch06.teamclient.GetTeamResponse")
    @Action(input = "http://ch06.com/Teams/getTeamRequest", output = "http://ch06.com/Teams/getTeamResponse")
    public Team getTeam(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.ch06.teamclient.Team>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeams", targetNamespace = "http://ch06.com/", className = "com.ch06.teamclient.GetTeams")
    @ResponseWrapper(localName = "getTeamsResponse", targetNamespace = "http://ch06.com/", className = "com.ch06.teamclient.GetTeamsResponse")
    @Action(input = "http://ch06.com/Teams/getTeamsRequest", output = "http://ch06.com/Teams/getTeamsResponse")
    public List<Team> getTeams();

}
