 

<html>
<head>
	
	<title>Verizon Wireless</title>

</head>
	
<body bgcolor="" text="#000000" link="#666666" alink="#666666" vlink="#666666" marginheight="0" topmargin="0">

<center><u><b>Terms and Conditions for Use of This Web Page</b></u></center>
<p>These web pages (the "Pages") are maintained by Verizon Wireless for use by software developers and content providers interested in obtaining information about the development of applications and/or content for possible use in connection with the wireless handsets of Verizon Wireless customers.  The Pages also provide software developers and content providers with the ability to register with Verizon Wireless and, under certain circumstances, provide Verizon Wireless with the data needed by it to evaluate their applications and/or content.
<p>When you or any other person, employee or representative authorized by you (collectively referred to as "You"), use the Pages, You accept the terms and conditions stated below (this "User Agreement").  Do not use the Pages if You do not agree to the terms and conditions of the User Agreement.
<p>As set forth below, You acknowledge and agree that the Pages are not (i) a request for proposals, (ii) an order for applications or content, (iii) a commitment to purchase or use any applications or content in the future, or (iv) a guarantee that any applications or content, or any other data, submitted by You to Verizon Wireless via the Pages will be treated as confidential or proprietary or protected from disclosure.
<p><b>A.	USE OF THE PAGES</b><ol>
<b><li>Limited License.</b>  Subject to the terms and conditions of this User Agreement, Verizon Wireless grants You a personal, revocable, limited use, non-exclusive, non-transferable, non-sublicensable license to access and use the Pages during the Term (as defined below) of this User Agreement.<p></li>
<b><li>License Limitations.</b>
<p>You are responsible for providing, at Your own expense, all communications lines, hardware, software, services, and other materials and technology necessary for You to access the Pages.  Verizon Wireless shall have no responsibility for any failure of such items or any failure or limitation of the Internet or other computer hardware or software.
<p>You are not permitted to download, copy, or otherwise use the Pages, or any information available on the Pages, in whole or part, except as expressly permitted by this User Agreement.  
<p>You are not permitted to distribute, assign, transfer, or sublicense any right to use the Pages, either in whole or part, to any third party.
<p>The source code of the Pages is confidential and proprietary to Verizon Wireless and/or its licensors.  Accordingly, You may not decompile, disassemble, reverse engineer or otherwise manipulate the source code for the Pages, and neither may You use any software to derive such source code.<p></li>
<b><li>Privacy.</b>  It is the policy of Verizon Wireless to respect the privacy of its customers and any persons who visit its web sites.  For this reason, Verizon Wireless has established a Privacy Statement, the terms of which are available for Your review at the following URL: http://www.VerizonWireless.com/privacy.html.  Said Privacy Statement is incorporated into this User Agreement by this reference.<p></li>
<b><li>Subject To Change.</b>  This User Agreement, the Privacy Statement, and the business policies and practices associated with the use of the Pages are subject to change by Verizon Wireless from time to time.  Likewise, Verizon Wireless reserves the right to modify the content on the Pages, without prior notice, at any time.  Your use of the Pages is Your agreement to be bound by such changes.<p></li>
<b><li>Term.</b>  The period during which You are entitled to use the Pages (the "Term") begins on the date upon which You agree to the terms and conditions contained in this User Agreement by accessing the Pages.  Verizon Wireless reserves the right, in its sole discretion and in addition to any other remedies available to it by law, rule, and regulation, to terminate this User Agreement at any time, without notice, if You breach any of the terms and conditions hereof.  Additionally, either You or Verizon Wireless may terminate this User Agreement at any time without cause, however, termination of this User Agreement shall not relieve you of the obligations under this User Agreement that you assumed by using the Pages.<p></li>
<b><li>Limitations On Use Of The Pages.</b>
<p>You acknowledge that the Internet is a network of computers worldwide, and that any information or data submitted by You to Verizon Wireless, or by You to third parties via the Internet, may be routed via third party computers on the Internet.  You also acknowledge that Verizon Wireless is not responsible for lapses in online security, and that Verizon Wireless does not assume liability for improper use of Your information or data by third parties.
<p>You may view, download, and print content from the Pages subject to the following conditions:<p><ol type="i">
<li>the content may be used solely for informational purposes;<p></li>
<li>the content may not be modified or altered in any way; and<p></li>
<li>You may not republish, distribute, prepare derivative works from, or otherwise use the content other than as explicitly permitted herein.<p></li></ol>
You do not acquire any ownership rights to any content in the Pages by virtue of using the Pages.
<p>Without limiting the generality of the foregoing, in consideration for Verizon Wireless providing access to the Pages, You agree not to use or access the Pages to:
<ol type="i"><p>
<li>violate any applicable law, rule, or regulation;<p></li>
<li>harass, offend, threaten, embarrass, distress, or invade the privacy of any individual or entity;<p></li>
<li>post or transmit any unsolicited commercial, advertising, or promotional materials, including, without limitation, "SPAM" or mass distributions;<p></li>
<li>provide false information to Verizon Wireless or impersonate another person at any point; and/or<p></li>
<li>transmit any material that infringes upon, misuses, and/or misappropriates any third party's copyright, trademark, patent, trade secret, or other intellectual property right.<p></li>
</ol>
If You, Your employees or Your authorized representatives violate the terms and conditions contained in this User Agreement, Verizon Wireless may, without prior notice and without liability, terminate this User Agreement, terminate Your use of and access to the Pages and/or take any other action deemed appropriate in its sole discretion.<p>
<b><li>Third Party Web Sites And Information.</b>
<p>The Pages may provide hyperlinks to third party web sites.  Verizon Wireless does not control, endorse, or guarantee content found in such web sites.  You agree that Verizon Wireless is not responsible for any content, associated links, resources, or services associated with third party web sites.  You further agree that Verizon Wireless shall not be liable for any loss or damage of any sort associated with Your use of or access to third party web sites.  Any hypertext links or access to third party web sites are provided for Your convenience only.<p></li>
<b><li>Disclaimer Of Endorsement.</b>  Reference in the Pages to any products, services, processes, hypertext links to third parties, or other information by trade name, trademark, manufacturer, supplier, or otherwise does not necessarily constitute or imply their endorsement, sponsorship, or recommendation by Verizon Wireless.  Products, services, processes, and hypertext links information is Your sole responsibility.  The Verizon Wireless name and logo and other trademarks and trade names owned by Verizon Communication and/or Verizon Wireless may not be used in any commercial manner without the prior written consent of Verizon Communications and Verizon Wireless.<p></li>
<b><li>Consent To Monitoring And Disclosure.</b><p>
Verizon Wireless is under no obligation to monitor the information or content available or transmitted through the Pages.  However, You agree that Verizon Wireless may monitor such information and content in order to: (a) comply with any applicable laws, rules, or regulations or other governmental orders; (b) to administer the Pages properly; and/or (c) to protect itself, You and other users of the Pages.
<p>Should You provide Verizon Wireless or its contractors or agents with information, including, but not limited to, feedback, data, answers, questions, comments, suggestions, plans, ideas, or the like, such information shall be deemed to be non-confidential, and Verizon Wireless assumes no obligation to protect such information from disclosure.  Verizon Wireless shall be free to reproduce, use, disclose, and distribute such information to others without restriction, and You acknowledge that Verizon Wireless has absolutely no liability for alleged infringement or misappropriation in connection with such information.  The submission of such information to Verizon Wireless shall in no way prevent, or require, the purchase, manufacture, or use of any products, services, plans, or ideas by Verizon Wireless for any purpose whatever.
<b><li>Administration Of Pages.</b>  You acknowledge that Verizon Wireless may, from time to time, without notice to You and at its sole discretion, establish various practices, limitations, and restrictions for administering the Pages, including, without limitation, how often the Pages may be accessed.  You also agree that Verizon Wireless is not responsible or liable for deactivation or deletion of information or content resulting from, or arising out of, administration of the Pages.
</ol>
<p><b>B.	REGISTRATION AND DATA SUBMISSION PROCESS</b><p>
In the event that You register with Verzion Wireless via the Pages, or provide information to Verizon Wireless via the Pages about existing or proposed applications and/or content, You will submit certain data to Verizon Wireless via the Pages.  When You submit such data to Verizon Wireless via the Pages, at the "Verizon Wireless Content and Application Developer Community Registration" and "Submit an Application or Content" web pages, including, without limitation, writings, drawings, sound recordings, computer programs and codes, system specifications, pictorial representations, and graphs, You agree as set forth below.
<ol><p>
<b><li>No Confidential Information.</b><p></li>
No data that You provide to Verizon Wireless via the Pages will be confidential or proprietary.  Further, Your confidential use of the Pages cannot be guaranteed by Verizon Wireless, and Verizon Wireless shall not be responsible for any harm that You may suffer as a result of a breach of confidentiality in respect to Your use of the Pages.  In other words, Verizon Wireless shall have no obligation to protect from disclosure any data that You supply via the Pages.<p></li>
<b><li>Obligations Of The Parties.</b>  Verizon Wireless shall have no obligation to use any of the data provided by You via the Pages, or any of the applications or content to which such data relates, and neither shall it have any other obligation to You by virtue of Your provision of the data.<p></li>
<b><li>The Application License Agreement.</b>  Should You decide to provide data to Verizon Wireless via the Pages about existing or proposed applications and/or content, You will be required to review and signify, by clicking, that You accept the terms and conditions of a "License Agreement" between You and Verizon Wireless.  This is the agreement that would govern Your relationship with Verizon Wireless should Verizon Wireless decide to make any of the applications or content about which you provide data available for use on the wireless handsets of Verizon Wireless customers.  The terms and conditions in such agreement will begin to govern the relationship between You and Verizon Wireless with respect to the subject application(s) and/or content at the time, and for the duration, set forth in the agreement.<p></li>
</ol>
<p><b>C.	GENERAL TERMS</b><p>
<ol>
<b><li>Trademarks.</b>  The Verizon Wireless name, trade names, trademarks, and logo, as well as all related product and service names, design marks, and slogans, are the property of Verizon Communications and/or Verizon Wireless.  All other names, marks, and logos are the names, marks, and logos of their respective owners.  All right, title, and interest, including, without limitation, all copyrights, trademarks, and other intellectual property rights, in the Pages belong to Verizon Wireless or any third party suppliers (or other licensors).<p></li>
<b><li>Copyright.</b><p>
The information and content available on or accessible through the Pages is the copyrighted property of Verizon Wireless, its licensors, a vendor or other applicable licensor.  Permission to copy and distribute such information and content is granted subject to the following restrictions: (a) the information and content is provided for personal, non-commercial use only; and (b) any copies of the information and content made by You with the permission of Verizon Wireless must include the appropriate copyright notice.  This copyright notice is as follows: "Copyright© 2007 Verizon Wireless.  All rights reserved."  You may access the Verizon Wireless copyright policy at http://www.VerizonWireless.com/copyright.html. 
<p>All information and content made available on or accessible through the Pages may contain other proprietary notices or describe products, services, processes, or technologies owned by Verizon Wireless or third parties.  Nothing contained in this User Agreement shall be construed as granting You a license under any copyright, trademark, patent, or other intellectual property right of Verizon Wireless, Verizon Communications or any third party.
<p>The Pages and the information and content within the Pages are the property of Verizon Wireless or its suppliers and they are protected by United States copyright laws and international treaty provisions.  The compilation, organization, and display of the information and content, as well as all software and inventions used on and in connection with the Pages, are the exclusive property of Verizon Wireless.  Verizon Wireless reserves all rights in the Pages and the content available via the Pages which are not specifically granted in any agreements with Verizon Wireless or in this User Agreement.<p></li>
<b><li>Limitation Of Liability.</b><p>
VERIZON WIRELESS, AND ITS OFFICERS, EMPLOYEES, CONTRACTORS, SUPPLIERS, AGENTS, SUBSIDIARIES, AND AFFILIATES, WILL NOT BE LIABLE FOR ANY SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM AN INABILITY TO ACCESS OR USE THE PAGES AND/OR THE LOSS OF ANY INFORMATION OR CONTENT AVAILABLE ON OR ACCESSIBLE THROUGH THE PAGES, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, STRICT LIABILITY, OR OTHER TORTIOUS ACTION OR LEGAL BASIS, ARISING OUT OF OR IN CONNECTION WITH THE INFORMATION OR CONTENT AVAILABLE ON OR ACCESSIBLE THROUGH THE PAGES, EVEN IF VERIZON WIRELESS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  YOU AGREE AND ACKNOWLEDGE THAT THESE LIMITATIONS ON THE LIABILITY OF VERIZON WIRELESS REFLECT A REASONABLE ALLOCATION OF RISK AND THAT SUCH ALLOCATION OF RISK IS A SIGNIFICANT INDUCEMENT FOR VERIZON WIRELESS TO ALLOW YOU TO ACCESS AND USE THE PAGES.
<p>In no event will the aggregate, total liability of Verizon Wireless for damages, injury, losses, and causes of action, whether in contract, tort, or otherwise, arising from or relating to access or use of the Pages exceed One Hundred Dollars ($100.00).  Because some jurisdictions do not allow the limitation or exclusion of liability for incidental or consequential damages, some of the above limitations may not apply in those jurisdictions.  In such jurisdictions, Verizon Wireless' liability is limited to the greatest extent permitted by law.<p></li>
<b><li>Disclaimer Of Warranties.</b><p>
YOU ASSUME ALL RESPONSIBILITY AND RISK FOR USE OF THE PAGES AND THE INTERNET GENERALLY.  ACCESS TO AND/OR USE OF INFORMATION, CONTENT, PRODUCTS AND/OR SERVICES PROVIDED ON OR AVAILABLE THROUGH THE PAGES ARE PROVIDED OR MADE AVAILABLE ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE, NON-INFRINGEMENT, OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  NO ADVICE OR INFORMATION GIVEN BY VERIZON WIRELESS, ITS PARENT, ITS AFFILIATES, OR ITS CONTRACTORS OR AGENTS SHALL CREATE ANY WARRANTY.  FURTHER, NEITHER VERIZON WIRELESS NOR ITS AFFILIATES OR CONTRACTORS WARRANT THAT INFORMATION, CONTENT, PRODUCTS, AND/OR SERVICES PROVIDED ON OR AVAILABLE THROUGH THE PAGES WILL BE UN-INTERRUPTIBLE, ACCURATE, COMPLETE, USEFUL, FUNCTIONAL, OR ERROR FREE, OR THAT ANY SOFTWARE OR OTHER MATERIAL PROVIDED ON OR AVAILABLE THROUGH THE PAGES IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
<p>Any Verizon Wireless information or content available or transmitted through the Pages may include technical inaccuracies or typographical errors.  Verizon Wireless has the right to make changes and updates to any of this information or content without notice at any time.<p></li>
<b><li>Indemnification.</b>  You agree to indemnify and hold Verizon Wireless, its parent, its affiliates, and/or its contractors and agents harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of Your access to or use of the Pages, the violation by You of this User Agreement, or the infringement by You of any intellectual property or other right of any person or entity.<p></li>
<b><li>Severability.</b>  In the event that any provision of this User Agreement is found to be invalid, illegal, or unenforceable, the validity, legality, and enforceability of any of the remaining provisions shall not in any way be affected or impaired, and a valid, legal, and enforceable provision of similar intent and economic impact shall be substituted therefore.<p></li>
<b><li>Jurisdiction Statement.</b>  Verizon Wireless does not conduct business in those individual States where it does not offer wireless service, and it does not agree to the jurisdiction of the State court in those individual States.  Further, Verizon Wireless does not consent to the jurisdiction of such State courts merely by virtue of its operating and transmitting the Pages.<p></li>
<b><li>Publicity. </b> Nothing contained in this User Agreement shall be construed as granting to You any right to use or refer to in advertising, publicity, promotion, marketing, or other activities, any name, trade name, trade or service mark, or any other designation of Verizon Wireless, including any contraction, abbreviation or simulation of any kind of the foregoing, unless Verizon Wireless first provides its prior written consent to such usage.<p></li>
<b><li>International Use.</b>  Verizon Wireless does not represent that all information and data accessible via the Pages is appropriate or available for use in all geographic locations, especially some locations outside the United States, and accessing such from certain locations may be illegal and prohibited.  Those who do access such information and data from such locations act on their own initiative, and Verizon Wireless is not responsible for their compliance with local laws or other applicable legal or regulatory restrictions.  You agree that You will not access the foregoing where prohibited by applicable law, rule or regulation.<p></li>
<b><li>Governing Law.</b>  The Pages shall be governed by and construed in accordance with the laws of the State of New York, excluding its conflict of law provisions.  If any provision(s) of this User Agreement is held by a court of competent jurisdiction to be contrary to law, then such provision(s) shall be construed, as nearly as possible, to reflect the intentions of the parties with the other provisions remaining in full force and effect.<p></li>
<b><li>Digital Millennium Copyright Act ("DMCA") Notice.</b>  Verizon Wireless owns, protects, and enforces copyrights in its own creative material and respects the copyright properties of others.  In addition to Verizon Wireless' wireless services, it offers added value services as a "services provider", as that term is defined in the DMCA, including services as a web site provider and portal with links to third party web sites.  As a result, materials of third parties, not owned or controlled by Verizon Wireless, may be transmitted, stored, accessed, or otherwise made available through use of the Pages.  To the best of Verizon Wireless' knowledge, these materials do not infringe the copyrights of others.  You should notify Verizon Wireless promptly if this is not the case.  Upon Verizon Wireless' receipt of a proper notice of claimed infringement under the DCMA, Verizon Wireless will respond expeditiously to remove, or disable access to, the material claimed to be infringing and will follow the procedures specified in the DMCA to resolve the claim between the notifying party and the alleged infringer who provided the material at issue.  The designated agent (i.e., proper party) to whom You should address such notice is: Verizon Wireless, Associate General Counsel - Sales, Marketing and Consumer Law, 180 Washington Valley Road, Bedminster, New Jersey 07921, telephone number (908) 306-7000.  It is the policy of Verizon Wireless to terminate its contractual relationships regarding materials with third parties who repeatedly infringe the copyrights of others.  To learn more about this policy, contact Verizon Wireless.<p></li>
<b><li>Security.</b>  You may establish a profile or account via the Pages that may be protected by a user identification code and/or password.  You are responsible for maintaining the confidentiality and security of Your user identification code and/o password, as well as other profile and/or account information, and You are fully responsible for all conduct carried out under the profile and/or account.  Verizon Wireless is not liable for any loss of confidentiality or for any damages arising from your failure to comply with these terms.<p></li>
<b><li>Miscellaneous.</b><p>
Should You be unwilling to accept the terms and conditions of this User Agreement after initialing accepting such terms and conditions, You may terminate this User Agreement at any time and stop using the Pages.
<p>Verizon Wireless' failure to exercise or enforce any right or provision of this User Agreement shall not constitute a waiver of such right or provision unless acknowledged and agreed to by Verizon Wireless in writing.
<p>Neither the course of conduct between the parties nor trade practice shall act to modify any provision of this User Agreement.
<p>You and Verizon Wireless agree that any cause of action arising out of or related to Your access to or use of the Pages must commence within one (1) year after the cause of action arises, otherwise, such cause of action is permanently barred.  Because some jurisdictions do not permit such time bars, this limitation may not apply in all situations.
<p>If any provision(s) of this User Agreement is held by a court of competent jurisdiction to be contrary to law, then such provision(s) shall be construed, as nearly as possible, to reflect the intentions of the parties with the other provisions remaining in full force and effect.<p></li>
</ol>
<p>If You have any questions regarding this User Agreement, please contact Verizon Wireless at www.verizonwireless.com.<p><br><br><br>

				<a href="http://www.verizonwireless.com" target="new" style="font-weight: normal;">Verizon Wireless</a>  | 
				<a href="#" onclick="return false" style="font-weight: normal;">Terms and Conditions</a> | 
				<a href="#" onclick="return false" style="font-weight: normal;">Copyright &copy; 2009 Verizon</a> | 
				<a href="http://www.verizonwireless.com/privacy.html" target="new" style="font-weight: normal;">Privacy Statement</a>
		

</body>
</html>
