/* Generated by Together */

package com.netpace.vzdn.service.impl;

abstract public class BaseEventHandler implements EventHandler
{
    public void handleEvent(VzdnEventObject eventObj)
    {
        // Write your code here
    }
    
}
