Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (82, 'New Alliances', 'New Alliances', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2, 'NEW_ALLIANCES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (83, 'Search Alliances', 'Search Alliances', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 3, 'SEARCH_ALLIANCES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (84, 'Alliance Summary', 'Alliance Summary', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 4, 'ALLIANCE_STATUS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (85, 'Company Information', 'Company Info', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 5, 'COMPANY_INFORMATION', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (86, 'Business Information', 'Business Info', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 6, 'BUSINESS_INFORMATION', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (87, 'Contact Information', 'Contact Info', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 7, 'CONTACT_INFORMATION', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (88, 'Alliance Contracts', 'Contracts', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 8, 'ALLIANCE_CONTRACTS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (90, 'Important Information', 'Important Info', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 10, 'SPOTLIGHT_PAGE', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (91, 'All Applications', 'All Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 11, 'ALL_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (92, 'Search Applications', 'Search Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 12, 'SEARCH_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (93, 'My Applications', 'My Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 13, 'MY_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (94, 'New Applications', 'New Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 14, 'NEW_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (95, 'Saved Applications', 'Saved Applications', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 15, 'SAVED_APPLICATIONS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (144, 'My Alliances', 'My Alliances', 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 68, 'DEVICES_ON_LOAN', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (147, 'Manage Contracts', 'Manage Contracts', 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 69, 'MANAGE_CONTRACTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (148, 'Amendments', 'Amendments', 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/0003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 70, 'AMENDMENTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (150, 'Manage App Tab Manage Info', 'Manage App Tab Manage Info', 'system', TO_DATE('01/14/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('01/14/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_TAB_MANAGE_INFO', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (151, 'Legal User Restrictions', 'Legal User Restrictions', 'system', TO_DATE('01/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('01/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'LEGAL_USER', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (152, 'All Alliances', 'All Alliances', 'system', TO_DATE('01/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('01/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, 'ALL_ALLIANCES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (162, 'Manage Brew Apps', 'Manage Brew Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_BREW', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (163, 'Manage Enterprise Apps', 'Manage Enterprise Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_ENTERPRISE', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (164, 'Manage MMS Apps', 'Manage MMS Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_MMS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (165, 'Manage SMS Apps', 'Manage SMS Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_SMS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (166, 'Manage WAP Apps', 'Manage WAP Applications', 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/06/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_WAP', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (167, 'Roles', 'Manage Roles', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 37, 'ROLES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (168, 'Users', 'Manage Users', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 38, 'USERS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (169, 'Manage Brew Information Section in Application Processing Interface', 'Manage Brew Information Section in Application Processing Interface', 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_BREW_RELATED_INFO', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (170, 'Manage Assign Section in Application Processing Information Interface', 'Manage Assign Section in Application Processing Information Interface', 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_ASSIGN', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (171, 'Manage Prioritization Section in Application Processing Interface', 'Manage Prioritization Section in Application Processing Interface', 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_PRIORITIZATION', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (172, 'Manage Testing Section in Application Processing Interface', 'Manage Testing Section in Application Processing Interface', 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_TESTING', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (173, 'Manage Brew Production Information Section in Application Processing Interface', 'Manage Brew Production Information Section in Application Processing Interface', 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/03/2004 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'SECTION_APP_PROCESS_INFO_BREW_PROD_INFO', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (189, 'Submit Sales Lead', 'Submit Sales Lead', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 79, 'SUBMIT_SALES_LEAD', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (192, 'Manage Sales Leads', 'Manage Sales Leads', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 16, 'MANAGE_SALES_LEADS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (200, 'Brew Evaluation Information', 'Brew Evaluation Information', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'BREW_EVALUATION_INFO', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (250, 'Application Evaluation Form', 'Application Evaluation Form', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'APP_EVALUATION_FORM', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (255, 'New BREW Applications', 'New BREW Applications', 'system', TO_DATE('05/22/2004 22:46:19', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/22/2004 22:46:19', 'MM/DD/YYYY HH24:MI:SS'), 74, 'NEW_BREW_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (256, 'New Enterprise Applications', 'New Enterprise Applications', 'system', TO_DATE('05/22/2004 22:46:19', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/22/2004 22:46:19', 'MM/DD/YYYY HH24:MI:SS'), 75, 'NEW_ENTERPRISE_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (257, 'New MMS Applications', 'New MMS Applications', 'system', TO_DATE('05/22/2004 22:46:19', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/22/2004 22:46:19', 'MM/DD/YYYY HH24:MI:SS'), 76, 'NEW_MMS_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (258, 'New SMS Applications', 'New SMS Applications', 'system', TO_DATE('05/22/2004 22:46:19', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/22/2004 22:46:19', 'MM/DD/YYYY HH24:MI:SS'), 77, 'NEW_SMS_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (259, 'New WAP Applications', 'New WAP Applications', 'system', TO_DATE('05/22/2004 22:46:20', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/22/2004 22:46:20', 'MM/DD/YYYY HH24:MI:SS'), 78, 'NEW_WAP_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (260, 'New BREW Concepts', 'New BREW Concepts', 'system', TO_DATE('08/01/2004 13:39:09', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('08/01/2004 13:39:09', 'MM/DD/YYYY HH24:MI:SS'), 81, 'NEW_BREW_CONCEPTS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (261, 'Search Program Guide', 'Search Program Guide', 'system', TO_DATE('09/03/2004 15:42:30', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/03/2004 15:42:30', 'MM/DD/YYYY HH24:MI:SS'), 82, 'SEARCH_PROGRAM_GUIDE', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (262, 'Provisioned Apps', 'Provisioned Apps', 'system', TO_DATE('10/15/2004 17:53:20', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/15/2004 17:53:20', 'MM/DD/YYYY HH24:MI:SS'), 17, 'PROVISIONED_APPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (263, 'Manage Provisioned Apps', 'Manage Provisioned Apps', 'system', TO_DATE('09/09/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/09/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_PROV_APPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (264, 'Manage Initial Approval Section in Wap Application''s Processing Information Page', 'Manage Initial Approval Section in Wap Application''s Processing Information Page', 'system', TO_DATE('02/19/2005 12:19:58', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/19/2005 12:19:58', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_INITIAL_APPROVAL', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (265, 'Manage Initial Buisness Approval Section in Wap Application''s Processing Information Page', 'Manage Initial Business Approval Section in Wap Application''s Processing Information Page', 'system', TO_DATE('02/19/2005 12:19:58', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/19/2005 12:19:58', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_INITIAL_BUSINESS_APPROVAL', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (266, 'Manage Move to Pending DCR  Section in Wap Application''s Processing Information Page', 'Manage Move to Pending DCR Section in Wap Application''s Processing Information Page', 'system', TO_DATE('02/19/2005 12:19:59', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/19/2005 12:19:59', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_MOVE_TO_PENDING_DCR', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (267, 'Manage Pending DCR  Section in Wap Application''s Processing Information Page', 'Manage Pending DCR Section in Wap Application''s Processing Information Page', 'system', TO_DATE('02/19/2005 12:19:59', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/19/2005 12:19:59', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_PENDING_DCR', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (268, 'Manage Content Testing Section in Wap Application''s Processing Information Page', 'Manage Content Testing Section in Wap Application''s Processing Information Page', 'system', TO_DATE('02/19/2005 12:19:59', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/19/2005 12:19:59', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_CONTENT_TESTING', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (269, 'Manage Content Completion Section in Wap Application''s Processing Information Page', 'Manage Content Completion Section in Wap Application''s Processing Information Page', 'system', TO_DATE('02/19/2005 12:19:59', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/19/2005 12:19:59', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_CONTENT_COMPLETION', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (270, 'Manage Content Removal Section in Wap Application''s Processing Information Page', 'Manage Content Removal Section in Wap Application''s Processing Information Page', 'system', TO_DATE('02/19/2005 12:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/19/2005 12:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_APP_MANAGE_SECTION_CONTENT_REMOVAL', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (278, 'Create Application', 'Create Application', 'system', TO_DATE('02/19/2005 12:26:01', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/19/2005 12:26:01', 'MM/DD/YYYY HH24:MI:SS'), 83, 'CREATE_APPLICATION', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (279, 'Manage VCAST Apps', 'Manage VCAST Apps', 'system', TO_DATE('06/09/2005 17:08:12', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('06/09/2005 17:08:12', 'MM/DD/YYYY HH24:MI:SS'), 'MANAGE_APP_VCAST', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (300, 'Contact Technical Support', 'Contact Technical Support', 'system', 72, 'CONTACT_TECH_SUPPORT', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, LAST_UPDATED_BY, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (301, 'View FAQs', 'View FAQs', 'system', 'system', 31, 'FAQ', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, LAST_UPDATED_BY, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (302, 'View Hot Topics', 'View Hot Topics', 'system', 'system', 32, 'TOPICS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, LAST_UPDATED_BY, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (303, 'Discussion Forum', 'Discussion Forum', 'system', 'system', 29, 'FORUM', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, LAST_UPDATED_BY, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (304, 'Manage Discussion Forum', 'Manage Discussion Forum', 'system', 'system', 30, 'MANAGE_FORUM', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, LAST_UPDATED_BY, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (305, 'Manage FAQs', 'Manage FAQs', 'system', 'system', 33, 'MANAGE_FAQS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, LAST_UPDATED_BY, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (306, 'Manage Topics', 'Manage Topics', 'system', 'system', 34, 'MANAGE_TOPICS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, LAST_UPDATED_BY, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (307, 'Manage Users', 'Manage Users', 'system', 'system', 14, 'ALLIANCE_USERS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, LAST_UPDATED_BY, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (308, 'Tools', 'Tools', 'system', 'system', 51, 'TOOLS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, LAST_UPDATED_BY, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (309, 'Devices on Loan', 'Devices on Loan', 'system', 'system', 102, 'DEVICES_ON_LOAN', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (310, 'User Defined Report', 'User Defined Report', 'system', TO_DATE('05/01/2004 22:50:00', 'MM/DD/YYYY HH24:MI:SS'), 10, 'UREPORTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (311, 'Devices', 'Manage Devices', 'system', TO_DATE('05/02/2004 00:08:00', 'MM/DD/YYYY HH24:MI:SS'), 48, 'DEVICES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (312, 'Manage FAQ Categories', 'Manage FAQ Categories', 'system', TO_DATE('05/02/2004 12:35:00', 'MM/DD/YYYY HH24:MI:SS'), 73, 'MANAGE_FAQ_CATEGORIES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (313, 'Reconcile Catalog Data ', 'Reconcile Live Apps', 'system', TO_DATE('05/08/2004 19:59:00', 'MM/DD/YYYY HH24:MI:SS'), 20, 'RECONCILE_CATALOG_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (314, 'Upload Catalog Data', 'Upload NSTL Spreadsheet of launched applications', 'system', TO_DATE('05/08/2004 20:02:00', 'MM/DD/YYYY HH24:MI:SS'), 19, 'UPLOAD_CATALOG_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (315, 'Inbox', 'Message Center Inbox', 'system', TO_DATE('07/02/2004 20:10:00', 'MM/DD/YYYY HH24:MI:SS'), 21, 'INBOX', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (316, 'Outbox', 'Message center Outbox', 'system', TO_DATE('07/02/2004 20:12:00', 'MM/DD/YYYY HH24:MI:SS'), 22, 'OUTBOX', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (317, 'Manage Notifications', 'Manage Event Notifications', 'system', TO_DATE('07/02/2004 20:25:00', 'MM/DD/YYYY HH24:MI:SS'), 80, 'MANAGE_NOTIFICATIONS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (318, 'Canned Messages', 'Manage Canned Messages', 'system', TO_DATE('07/11/2004 10:48:00', 'MM/DD/YYYY HH24:MI:SS'), 52, 'EMAIL_MESSAGES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (319, 'Email Groups', 'Manage Email Groups', 'system', TO_DATE('07/11/2004 10:50:00', 'MM/DD/YYYY HH24:MI:SS'), 53, 'EMAIL_GROUPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (505, 'Upload Device on Loan Data', 'Upload Device on Loan Data', 'system', TO_DATE('02/05/2006 01:45:13', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/05/2006 01:45:13', 'MM/DD/YYYY HH24:MI:SS'), 101, 'UPLOAD_DEVICE_ON_LOAN_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (510, 'Manage Wap Application''s rollback to Pending DCR status', 'Manage Wap Application''s rollback to Pending DCR status', 'system', TO_DATE('05/27/2006 09:03:16', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('05/27/2006 09:03:16', 'MM/DD/YYYY HH24:MI:SS'), 103, 'WAP_APP_ROLLBACK_TO_PENDING_DCR', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (515, 'New VCAST Video Applications', 'New VCAST Video Applications', 'system', TO_DATE('06/05/2006 09:34:37', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('06/05/2006 09:34:37', 'MM/DD/YYYY HH24:MI:SS'), 104, 'NEW_VCAST_VIDEO_APPLICATIONS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (520, 'VCAST Music Information', 'VCAST Music', 'system', TO_DATE('08/04/2006 17:59:37', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('08/04/2006 17:59:37', 'MM/DD/YYYY HH24:MI:SS'), 110, 'VCAST_MUSIC_INFORMATION', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (525, 'All VCAST Music Alliances', 'All VCAST Music Alliances', 'system', TO_DATE('08/04/2006 17:59:50', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('08/04/2006 17:59:50', 'MM/DD/YYYY HH24:MI:SS'), 115, 'ALL_MUSIC_ALLIANCES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (530, 'Change Alliance Administrator', 'Change Alliance Administrator', 'system', TO_DATE('11/22/2006 18:25:19', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('11/22/2006 18:25:19', 'MM/DD/YYYY HH24:MI:SS'), 22, 'CHANGE_ALLIANCE_ADMIN', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (531, 'Wap FTP Manual', 'Wap FTP Manual', 'system', TO_DATE('11/12/2007 22:02:09', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('11/12/2007 22:02:09', 'MM/DD/YYYY HH24:MI:SS'), 'WAP_FTP_IMAGE_MANUAL', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (532, 'Upload WAP Icons', 'Upload WAP Icons', 'system', TO_DATE('11/12/2007 22:02:09', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('11/12/2007 22:02:09', 'MM/DD/YYYY HH24:MI:SS'), 116, 'UPLOAD_WAP_ICONS', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (533, 'Export Content Filter URLs', 'Export Content Filter URLs', 'system', TO_DATE('11/28/2007 20:42:40', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('11/28/2007 20:42:40', 'MM/DD/YYYY HH24:MI:SS'), 'EXPORT_CONTENT_FILTER_URLS', 'B');

