------------------------------------------------
------------------------------------------------
------------------------------------------------
-- Deleted Privileges not present on PROD
------------------------------------------------
------------------------------------------------
------------------------------------------------



Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (176, 'Upload NSTL Data', 'Upload NSTL Data', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 17, 'UPLOAD_NSTL_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (178, 'Application Categories', 'Application Categories', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 49, 'APP_CATEGORIES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (179, 'Application Subcategories', 'Application Subcategories', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 50, 'APP_SUB_CATEGORIES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (183, 'Sales Contacts', 'Sales Contacts', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 54, 'SALES_CONTACTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (190, 'Submit White Paper', 'Submit White Paper', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 13, 'SUBMIT_WHITE_PAPER', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (191, 'Reconcile NSTL Data', 'Reconcile NSTL Data', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 18, 'RECOMCILE_NSTL_DATA', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (193, 'Manage White Papers', 'Manage White Papers', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 6, 'MANAGE_WHITE_PAPERS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (196, 'Staff Performance Report', 'Staff Performance Report', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 39, 'STAFF_PERFORMANCE_REPORT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (197, 'Web Site Stats', 'Web Site Stats', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 40, 'WEBSITE_STATS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (198, 'GIN Report - Certified Apps', 'GIN Report - Certified Apps', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 41, 'GIN_REP_CERT_APPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (199, 'GIN Report - Accepted Apps', 'GIN Report - Accepted Apps', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 42, 'GIN_REP_ACCEPTED_APPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (201, 'GIN Report - Apps Under Testing', 'GIN Report - Apps Under Testing', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 43, 'GIN_REP_APPS_UNDER_TESTING', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (202, 'GIN Report - Live GIN', 'GIN Report - Live GIN', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 44, 'GIN_REP_LIVE_GIN', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (203, 'GIN Report - GIN History', 'GIN Report - GIN History', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 45, 'GIN_REP_GIN_HISTORY', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (210, 'Industry Focus', 'Industry Focus', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 55, 'INDUSTRY_FOCUS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (211, 'Programming Languages', 'Programming Languages', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 'PROGRAMMING_LANGUAGES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (212, 'Browsers', 'Browsers', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 57, 'BROWSERS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (213, 'VZW Platforms', 'VZW Platforms', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 58, 'VZW_PLATFORMS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (214, 'Features', 'Features', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 59, 'FEATURES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (215, 'Lines of Business', 'Lines of Business', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 60, 'LINES_OF_BUSINESS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (216, 'Certifications', 'Certifications', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 15, 'CERTIFICATIONS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (218, 'Live Chat', 'Live Chat', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 27, 'LIVE_CHAT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (219, 'Manage Chat Sessions', 'Manage Chat Sessions', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 28, 'MANAGE_CHAT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (220, 'Decks', 'Decks', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 71, 'DECKS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (271, 'Marketing User Module', 'Marketing User Module', 19, 'MARKETING_CONTENT_MODULE', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (272, 'Marketing Applications List', 'Marketing Applications List', 90, 'MARKETING_APP_LIST', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (273, 'Marketing Search Applications', 'Marketing Search Applications', 91, 'MARKETING_SEARCH_APP', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (274, 'Marketing Provisioned Applications', 'Marketing Provisioned Applications', 92, 'MARKETING_PROV_APP', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (275, 'Marketing Manage Content Requests', 'Marketing Manage Content Requests', 93, 'MARKETING_MANAGE_CONTENT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (276, 'Marketing VZW Administrator Content Request', 'Marketing content requests module for handling approvals of creative requests', 17, 'MARKETING_ADMIN_CONTENT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (277, 'Marketing Alliance Content Request', 'Interface for accepting application requested for creative contents', 18, 'MARKETING_ALLIANCE_CONTENT', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (280, 'Marketing Content', 'Content Request', 94, 'MARKETING_CONTENT', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (281, 'Provisioned Content', 'Provisioned Content', 95, 'NEW_PROVISIONED_CONTENTS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (282, 'Manage Marketing Content', 'Manage Marketing Content', 'system', TO_DATE('04/05/2005 18:22:51', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('04/05/2005 18:22:51', 'MM/DD/YYYY HH24:MI:SS'), 83, 'CP_MARKETING_CONTENT', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (283, 'Submit Marketing Content', 'Submit Marketing Content', 'system', TO_DATE('04/05/2005 18:22:51', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('04/05/2005 18:22:51', 'MM/DD/YYYY HH24:MI:SS'), 84, 'SUBMIT_MARKETING_CONTENT', 'A');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (503, 'Review Content Request', 'Review Content Request', 98, 'REVIEW_CONTENT_REQUEST', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (504, 'Applications For Legal Review', 'Applications For Legal Review', 'system', TO_DATE('11/23/2005 06:26:58', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('11/23/2005 06:26:58', 'MM/DD/YYYY HH24:MI:SS'), 100, 'APPLICATIONS_FOR_LEGAL_REVIEW', 'V');



------------------------------------------------
------------------------------------------------
------------------------------------------------
-- Deleted Privileges for new Phase 2
------------------------------------------------
------------------------------------------------
------------------------------------------------



Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (172, 'Inbox', 'Inbox', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 21, 'INBOX', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (173, 'Outbox', 'Outbox', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 22, 'OUTBOX', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (181, 'Email Messages', 'Email Messages', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 52, 'EMAIL_MESSAGES', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (182, 'Email Groups', 'Email Groups', 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('02/24/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 53, 'EMAIL_GROUPS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (186, 'Discussion Forum', 'Discussion Forum', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 29, 'FORUM', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (188, 'View Hot Topics', 'View Hot Topics', 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('10/17/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 32, 'TOPICS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (195, 'Manage Topics', 'Manage Topics', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 34, 'MANAGE_TOPICS', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (217, 'Manage Dicussion Forum', 'Manage Dicussion Forum', 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('03/16/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 30, 'MANAGE_FORUM', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (260, 'New BREW Concepts', 'New BREW Concepts', 'system', TO_DATE('07/27/2004 18:21:01', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('07/27/2004 18:21:01', 'MM/DD/YYYY HH24:MI:SS'), 80, 'NEW_BREW_CONCEPTS', 'B');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, SUB_MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (261, 'Search Program Guide', 'Search Program Guide', 'system', TO_DATE('08/30/2004 12:07:29', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('08/30/2004 12:07:29', 'MM/DD/YYYY HH24:MI:SS'), 81, 'SEARCH_PROGRAM_GUIDE', 'V');
Insert into AIMS_SYS_PRIVILEGES
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, MENU_ID, PRIVILEGE_KEY, AVAILABLE_TO)
 Values
   (262, 'Provisioned Apps', 'Provisioned Apps', 'system', TO_DATE('09/03/2004 14:45:42', 'MM/DD/YYYY HH24:MI:SS'), 'system', TO_DATE('09/03/2004 14:45:42', 'MM/DD/YYYY HH24:MI:SS'), 16, 'PROVISIONED_APPS', 'V');


