CREATE DATABASE /*!32312 IF NOT EXISTS*/`jforum_audit` /*!40100*/ DEFAULT CHARACTER SET utf8 ;

GRANT ALL ON jforum.* TO 'jforum_audit'@'%' IDENTIFIED BY 'jforum_audit';

USE jforum_audit;

CREATE TABLE jforum_api$aud ENGINE = INNODB AS SELECT api_id,api_key,api_validity,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_api WHERE 1 = 0;	
CREATE TABLE jforum_attach$aud ENGINE = INNODB AS SELECT attach_id,post_id,privmsgs_id,user_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_attach WHERE 1 = 0;	
CREATE TABLE jforum_attach_desc$aud ENGINE = INNODB AS SELECT attach_desc_id,attach_id,physical_filename,real_filename,download_count,description,mimetype,filesize,upload_time,thumb,extension_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_attach_desc WHERE 1 = 0;	
CREATE TABLE jforum_attach_quota$aud ENGINE = INNODB AS SELECT attach_quota_id,group_id,quota_limit_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_attach_quota WHERE 1 = 0;	
CREATE TABLE jforum_banlist$aud ENGINE = INNODB AS SELECT banlist_id,user_id,banlist_ip,banlist_email,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_banlist WHERE 1 = 0;	
CREATE TABLE jforum_banner$aud ENGINE = INNODB AS SELECT banner_id,banner_name,banner_placement,banner_description,banner_clicks,banner_views,banner_url,banner_weight,banner_active,banner_comment,banner_type,banner_width,banner_height,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_banner WHERE 1 = 0;	
CREATE TABLE jforum_bookmarks$aud ENGINE = INNODB AS SELECT bookmark_id,user_id,relation_id,relation_type,public_visible,title,description,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_bookmarks WHERE 1 = 0;	
CREATE TABLE jforum_categories$aud ENGINE = INNODB AS SELECT categories_id,title,display_order,moderated,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_categories WHERE 1 = 0;	
CREATE TABLE jforum_config$aud ENGINE = INNODB AS SELECT config_name,config_value,config_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_config WHERE 1 = 0;	
CREATE TABLE jforum_extension_groups$aud ENGINE = INNODB AS SELECT extension_group_id,name,allow,upload_icon,download_mode,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_extension_groups WHERE 1 = 0;	
CREATE TABLE jforum_extensions$aud ENGINE = INNODB AS SELECT extension_id,extension_group_id,description,upload_icon,extension,allow,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_extensions WHERE 1 = 0;	
CREATE TABLE jforum_forums$aud ENGINE = INNODB AS SELECT forum_id,categories_id,forum_name,forum_desc,forum_order,forum_topics,forum_last_post_id,moderated,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_forums WHERE 1 = 0;	
CREATE TABLE jforum_forums_watch$aud ENGINE = INNODB AS SELECT forum_id,user_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_forums_watch WHERE 1 = 0;	
CREATE TABLE jforum_groups$aud ENGINE = INNODB AS SELECT group_id,group_name,group_description,parent_id,vzdn_manager_role,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_groups WHERE 1 = 0;	
CREATE TABLE jforum_karma$aud ENGINE = INNODB AS SELECT karma_id,post_id,topic_id,post_user_id,from_user_id,points,rate_date,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_karma WHERE 1 = 0;	
CREATE TABLE jforum_mail_integration$aud ENGINE = INNODB AS SELECT forum_id,forum_email,pop_username,pop_password,pop_host,pop_port,pop_ssl,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_mail_integration WHERE 1 = 0;	
CREATE TABLE jforum_moderation_log$aud ENGINE = INNODB AS SELECT log_id,user_id,log_description,log_original_message,log_date,log_type,post_id,topic_id,post_user_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_moderation_log WHERE 1 = 0;	
CREATE TABLE jforum_posts$aud ENGINE = INNODB AS SELECT post_id,topic_id,forum_id,user_id,post_time,poster_ip,enable_bbcode,enable_html,enable_smilies,enable_sig,post_edit_time,post_edit_count,status,attach,need_moderate,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_posts WHERE 1 = 0;	
CREATE TABLE jforum_posts_text$aud ENGINE = INNODB AS SELECT post_id,post_text,post_subject,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_posts_text WHERE 1 = 0;	
CREATE TABLE jforum_privmsgs$aud ENGINE = INNODB AS SELECT privmsgs_id,privmsgs_type,privmsgs_subject,privmsgs_from_userid,privmsgs_to_userid,privmsgs_date,privmsgs_ip,privmsgs_enable_bbcode,privmsgs_enable_html,privmsgs_enable_smilies,privmsgs_attach_sig,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_privmsgs WHERE 1 = 0;	
CREATE TABLE jforum_privmsgs_text$aud ENGINE = INNODB AS SELECT privmsgs_id,privmsgs_text,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_privmsgs_text WHERE 1 = 0;	
CREATE TABLE jforum_quota_limit$aud ENGINE = INNODB AS SELECT quota_limit_id,quota_desc,quota_limit,quota_type,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_quota_limit WHERE 1 = 0;	
CREATE TABLE jforum_ranks$aud ENGINE = INNODB AS SELECT rank_id,rank_title,rank_min,rank_special,rank_image,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_ranks WHERE 1 = 0;	
CREATE TABLE jforum_role_values$aud ENGINE = INNODB AS SELECT role_id,role_value,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_role_values WHERE 1 = 0;	
CREATE TABLE jforum_roles$aud ENGINE = INNODB AS SELECT role_id,group_id,name,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_roles WHERE 1 = 0;	
CREATE TABLE jforum_sessions$aud ENGINE = INNODB AS SELECT session_id,session_user_id,session_start,session_time,session_ip,session_page,session_logged_int,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_sessions WHERE 1 = 0;	
CREATE TABLE jforum_smilies$aud ENGINE = INNODB AS SELECT smilie_id,code,url,disk_name,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_smilies WHERE 1 = 0;	
CREATE TABLE jforum_themes$aud ENGINE = INNODB AS SELECT themes_id,template_name,style_name,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_themes WHERE 1 = 0;	
CREATE TABLE jforum_topics$aud ENGINE = INNODB AS SELECT topic_id,forum_id,topic_title,user_id,topic_time,topic_views,topic_replies,topic_status,topic_vote_id,topic_type,topic_first_post_id,topic_last_post_id,topic_moved_id,moderated,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_topics WHERE 1 = 0;	
CREATE TABLE jforum_topics_watch$aud ENGINE = INNODB AS SELECT topic_id,user_id,is_read,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_topics_watch WHERE 1 = 0;	
CREATE TABLE jforum_user_groups$aud ENGINE = INNODB AS SELECT group_id,user_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_user_groups WHERE 1 = 0;	
CREATE TABLE jforum_users$aud ENGINE = INNODB AS SELECT user_id,user_active,username,user_password,user_session_time,user_session_page,user_lastvisit,user_regdate,user_level,user_posts,user_timezone,user_style,user_lang,user_dateformat,user_new_privmsg,user_unread_privmsg,user_last_privmsg,user_emailtime,user_viewemail,user_attachsig,user_allowhtml,user_allowbbcode,user_allowsmilies,user_allowavatar,user_allow_pm,user_allow_viewonline,user_notify,user_notify_always,user_notify_text,user_notify_pm,user_popup_pm,rank_id,user_avatar,user_avatar_type,user_email,user_icq,user_website,user_from,user_sig,user_sig_bbcode_uid,user_aim,user_yim,user_msnm,user_occ,user_interests,user_biography,user_actkey,gender,themes_id,deleted,user_viewonline,security_hash,user_karma,user_authhash,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_users WHERE 1 = 0;	
CREATE TABLE jforum_vote_desc$aud ENGINE = INNODB AS SELECT vote_id,topic_id,vote_text,vote_start,vote_length,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_vote_desc WHERE 1 = 0;	
CREATE TABLE jforum_vote_results$aud ENGINE = INNODB AS SELECT vote_id,vote_option_id,vote_option_text,vote_result,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_vote_results WHERE 1 = 0;	
CREATE TABLE jforum_vote_voters$aud ENGINE = INNODB AS SELECT vote_id,vote_user_id,vote_user_ip,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_vote_voters WHERE 1 = 0;	
CREATE TABLE jforum_words$aud ENGINE = INNODB AS SELECT word_id,word,replacement,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM jforum.jforum_words WHERE 1 = 0;	

GRANT ALL ON jforum_audit.* TO 'jforum'@'%' IDENTIFIED BY 'jforum';
GRANT ALL ON jforum.* TO 'jforum'@'%' IDENTIFIED BY 'jforum';