CREATE DATABASE /*!32312 IF NOT EXISTS*/`vzdn_audit` /*!40100*/ DEFAULT CHARACTER SET utf8 ;

GRANT ALL ON vzdn.* TO 'vzdn_audit'@'%' IDENTIFIED BY 'vzdn_audit';

USE vzdn_audit;

CREATE TABLE vzdn_dev_care_categories$aud ENGINE = INNODB AS SELECT category_id,category_name,created_by,created_date,updated_by,updated_date,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_dev_care_categories WHERE 1 = 0;	
CREATE TABLE vzdn_dev_care_issues$aud ENGINE = INNODB AS SELECT issue_id,title,description,category_id,ticket_id,user_id,attachment_name,sub_category_id,created_by,created_date,updated_by,updated_date,attachment_type,type_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_dev_care_issues WHERE 1 = 0;	
CREATE TABLE vzdn_dev_care_life_cycle$aud ENGINE = INNODB AS SELECT comment_id,comments,user_id,created_by,created_date,updated_by,updated_date,issue_id,type_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_dev_care_life_cycle WHERE 1 = 0;	
CREATE TABLE vzdn_dev_care_sub_categories$aud ENGINE = INNODB AS SELECT sub_category_id,sub_category_name,created_by,category_id,updated_by,updated_date,created_date,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_dev_care_sub_categories WHERE 1 = 0;	
CREATE TABLE vzdn_device_anywhere$aud ENGINE = INNODB AS SELECT id,useremail,datetime,gtm_company_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_device_anywhere WHERE 1 = 0;	
CREATE TABLE vzdn_email_messages$aud ENGINE = INNODB AS SELECT email_message_id,email_title,email_text,email_desc,email_category,created_by,created_date,last_updated_by,last_updated_date,from_address,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_email_messages WHERE 1 = 0;	
CREATE TABLE vzdn_email_messages_att$aud ENGINE = INNODB AS SELECT email_message_id,att_file_name,att_content_type,created_by,created_date,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_email_messages_att WHERE 1 = 0;	
CREATE TABLE vzdn_event_handlers$aud ENGINE = INNODB AS SELECT event_handler_id,event_id,class_name,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_event_handlers WHERE 1 = 0;	
CREATE TABLE vzdn_event_notifications$aud ENGINE = INNODB AS SELECT notification_id,message_id,event_id,notification_title,media,status,from_address,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_event_notifications WHERE 1 = 0;	
CREATE TABLE vzdn_event_place_holders$aud ENGINE = INNODB AS SELECT place_holder_id,event_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_event_place_holders WHERE 1 = 0;	
CREATE TABLE vzdn_events$aud ENGINE = INNODB AS SELECT event_id,event_name,event_desc,created_date,created_by,last_updated_date,last_updated_by,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_events WHERE 1 = 0;	
CREATE TABLE vzdn_menus$aud ENGINE = INNODB AS SELECT menu_id,menu_name,menu_url,image_name,sort_order,created_by,created_date,last_updated_by,last_updated_date,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_menus WHERE 1 = 0;	
CREATE TABLE vzdn_newsletters_log$aud ENGINE = INNODB AS SELECT log_id,email_subject,email_body,email_attachment,email_addresses,description,created_date,created_by,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_newsletters_log WHERE 1 = 0;	
CREATE TABLE vzdn_notif_ad_hoc_recipients$aud ENGINE = INNODB AS SELECT ad_hoc_id,notification_id,email_address,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_notif_ad_hoc_recipients WHERE 1 = 0;	
CREATE TABLE vzdn_notif_opt_out_recipients$aud ENGINE = INNODB AS SELECT notification_id,user_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_notif_opt_out_recipients WHERE 1 = 0;	
CREATE TABLE vzdn_notification_roles$aud ENGINE = INNODB AS SELECT notification_id,role_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_notification_roles WHERE 1 = 0;	
CREATE TABLE vzdn_place_holders$aud ENGINE = INNODB AS SELECT place_holder_id,place_holder_display_name,created_date,created_by,last_updated_date,last_updated_by,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_place_holders WHERE 1 = 0;	
CREATE TABLE vzdn_report_roles$aud ENGINE = INNODB AS SELECT report_id,role_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_report_roles WHERE 1 = 0;	
CREATE TABLE vzdn_reports$aud ENGINE = INNODB AS SELECT report_id,name,description,report_file,pdf_export,cvs_export,rtf_export,html_export,created_by,created_date,last_updated_by,last_updated_date,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_reports WHERE 1 = 0;	
CREATE TABLE vzdn_role_privileges$aud ENGINE = INNODB AS SELECT role_id,privilege_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_role_privileges WHERE 1 = 0;	
CREATE TABLE vzdn_sub_menus$aud ENGINE = INNODB AS SELECT sub_menu_id,sub_menu_name,sub_menu_url,image_name,sort_order,created_by,created_date,last_updated_by,last_updated_date,menu_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_sub_menus WHERE 1 = 0;	
CREATE TABLE vzdn_sys_privileges$aud ENGINE = INNODB AS SELECT privilege_id,privilege_name,privilege_description,created_by,created_date,last_updated_by,last_updated_date,menu_id,sub_menu_id,privilege_key,available_to,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_sys_privileges WHERE 1 = 0;	
CREATE TABLE vzdn_sys_roles$aud ENGINE = INNODB AS SELECT role_id,role_name,role_description,type_id,created_by,created_date,last_updated_by,last_updated_date,vzdn_role_mapping_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_sys_roles WHERE 1 = 0;	
CREATE TABLE vzdn_temp_files$aud ENGINE = INNODB AS SELECT temp_file_id,session_id,temp_file_name,temp_file_content_type,created_by,created_date,temp_file_comments,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_temp_files WHERE 1 = 0;	
CREATE TABLE vzdn_type_defs$aud ENGINE = INNODB AS SELECT type_def_id,type_name,type_description,created_by,created_date,last_updated_by,last_updated_date,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_type_defs WHERE 1 = 0;	
CREATE TABLE vzdn_types$aud ENGINE = INNODB AS SELECT type_id,type_def_id,type_value,description,sort_order,created_by,created_date,last_updated_by,last_updated_date,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_types WHERE 1 = 0;	
CREATE TABLE vzdn_user_roles$aud ENGINE = INNODB AS SELECT role_id,user_id,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_user_roles WHERE 1 = 0;	
CREATE TABLE vzdn_users$aud ENGINE = INNODB AS SELECT user_id,user_name,password,title,last_name,first_name,phone_number,security_question,security_answer,created_by,created_date,last_updated_by,last_updated_date,fax_number,mobile_number,newsletter_opt_out,status_type_id,user_type_id,manager_organization,page_size,gtm_comp_id,country,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_users WHERE 1 = 0;	
CREATE TABLE vzdn_zon_temp_users$aud ENGINE = INNODB AS SELECT user_id,username,user_type,title,first_name,last_name,phone_number,fax_number,mobile_number,password,'ABC' AUD_ACTION,CURRENT_TIMESTAMP AUD_TIMESTAMP,CURRENT_USER() AUD_USER FROM vzdn.vzdn_zon_temp_users WHERE 1 = 0;	

GRANT ALL ON vzdn_audit.* TO 'vzdn'@'%' IDENTIFIED BY 'vzdn';
GRANT ALL ON vzdn.* TO 'vzdn'@'%' IDENTIFIED BY 'vzdn';