package com.ttdev.ss;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

/**
 * This class was generated by Apache CXF 2.7.8 2013-12-24T10:07:49.750-08:00
 * Generated source version: 2.7.8
 * 
 */
public final class StatService_P1_Client {

	private static final QName SERVICE_NAME = new QName("http://ttdev.com/ss", "StatService");

	private StatService_P1_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = StatService_Service.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		StatService_Service ss = new StatService_Service(wsdlURL, SERVICE_NAME);
		StatService port = ss.getP1();

		/*{
			System.out.println("Invoking getStatisticsAsync...");
			java.lang.String _getStatisticsAsync_parameters = "";
			Response<java.lang.String> _getStatisticsAsync__return = port.getStatisticsAsync(_getStatisticsAsync_parameters);
			System.out.println("getStatisticsAsync.result="+ _getStatisticsAsync__return);
		}*/
		{
			System.out.println("Invoking getStatisticsAsync...");
			java.lang.String param = "Adnan Ahmed";			
			port.getStatisticsAsync(param, new AsyncHandler<String>() {

				@Override
				public void handleResponse(Response<String> res) {
					try {
						System.out.println("Got result: " + res.get());
					} catch (Exception e) {
						throw new RuntimeException(e);
					}
				}
			});
		}
		/*{
			System.out.println("Invoking getStatistics...");
			java.lang.String _getStatistics_parameters = "";
			java.lang.String _getStatistics__return = port.getStatistics(_getStatistics_parameters);
			System.out.println("getStatistics.result=" + _getStatistics__return);
		}*/

		System.out.println("Press Enter to quit");
		new BufferedReader(new InputStreamReader(System.in)).readLine();
		System.exit(0);
	}

}
