package com.ttdev.ss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-21T21:04:01.994-08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ttdev.com/ss", name = "WrappedService")
@XmlSeeAlso({ObjectFactory.class})
public interface WrappedService {

    @WebResult(name = "r", targetNamespace = "")
    @RequestWrapper(localName = "concat", targetNamespace = "http://ttdev.com/ss", className = "com.ttdev.ss.Concat")
    @WebMethod(action = "http://ttdev.com/ss/NewOperation")
    @ResponseWrapper(localName = "concatResponse", targetNamespace = "http://ttdev.com/ss", className = "com.ttdev.ss.ConcatResponse")
    public java.lang.String concat(
        @WebParam(name = "s1", targetNamespace = "")
        java.lang.String s1,
        @WebParam(name = "s2", targetNamespace = "")
        java.lang.String s2
    );
}
