
package com.ttdev.ss;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-21T21:04:01.936-08:00
 * Generated source version: 2.7.8
 * 
 */
public final class WrappedService_P1_Client {

    private static final QName SERVICE_NAME = new QName("http://ttdev.com/ss", "WrappedService");

    private WrappedService_P1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WrappedService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WrappedService_Service ss = new WrappedService_Service(wsdlURL, SERVICE_NAME);
        WrappedService port = ss.getP1();  
        BindingProvider bp = (BindingProvider)port;
        Map<String, Object> context = bp.getRequestContext();
        context.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "http://localhost:1234/ss/p1");
        {
        System.out.println("Invoking concat...");
        java.lang.String _concat_s1 = "Adnan";
        java.lang.String _concat_s2 = "Ahmed";
        java.lang.String _concat__return = port.concat(_concat_s1, _concat_s2);
        System.out.println("concat.result=" + _concat__return);
        }

        System.exit(0);
    }

}
