#Variables
TODAY_NOW=$(date +"%Y%m%d%H%M%S")
VZDNCORE_WAR_NAME=vzdncore
VZDNSITE_WAR_NAME=ROOT
TOMCAT_VZDNCORE_FOLDER_NAME=tomcat_vzdncore
TOMCAT_VZDNSITE_FOLDER_NAME=tomcat_vzdnsite
TOMCAT_VZDNCORE_HOME=/opt/vzdn/$TOMCAT_VZDNCORE_FOLDER_NAME
TOMCAT_VZDNSITE_HOME=/opt/vzdn/$TOMCAT_VZDNSITE_FOLDER_NAME
LINK_TO_FILE_SYSTEM_DATA_FOLDER=/opt/data
JAVA_HOME=/opt/java

echo $TODAY_NOW
cd $TOMCAT_VZDNCORE_HOME/webapps/$VZDNCORE_WAR_NAME/WEB-INF/classes
export CLASSPATH=$CLASSPATH:.:../lib/lucene-core-2.4.1.jar
export PATH=$PATH:$JAVA_HOME/bin
java org.apache.lucene.search.IndexHTML $LINK_TO_FILE_SYSTEM_DATA_FOLDER/fs/vzdnsite/index $TOMCAT_VZDNSITE_HOME/webapps/$VZDNSITE_WAR_NAME

