package spring.by.example.hibernate.model;

// Generated Mar 30, 2013 10:30:20 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer addressId;
	private Person person;
	private String address;
	private String city;
	private String state;
	private String zipPostal;
	private Date created;

	public Address() {
	}

	public Address(String city, String state, String zipPostal, Date created) {
		this.city = city;
		this.state = state;
		this.zipPostal = zipPostal;
		this.created = created;
	}

	public Address(Person person, String address, String city, String state,
			String zipPostal, Date created) {
		this.person = person;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zipPostal = zipPostal;
		this.created = created;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipPostal() {
		return this.zipPostal;
	}

	public void setZipPostal(String zipPostal) {
		this.zipPostal = zipPostal;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
