//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.26 at 11:06:38 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ttdev.com/bs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ttdev.bs;
