package com.ttdev.biz;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ttdev.biz.ProductQueryComplexType.QueryItem;
import com.ttdev.biz.ProductQueryResultComplexType.ResultItem;

/**
 * This class was generated by Apache CXF 2.7.8 2013-12-23T08:13:37.101-08:00
 * Generated source version: 2.7.8
 * 
 */
public final class BizService_BizServiceSOAP_Client {

	private static final QName SERVICE_NAME = new QName("http://foo.com",
			"BizService");

	private BizService_BizServiceSOAP_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = BizService_Service.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		BizService_Service ss = new BizService_Service(wsdlURL, SERVICE_NAME);
		BizService port = ss.getBizServiceSOAP();
		BindingProvider bp = (BindingProvider)port;
		Map<String, Object> ctx = bp.getRequestContext();
		ctx.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "http://localhost:1234/bizService");

		{
			System.out.println("Invoking query...");

			try {
				com.ttdev.biz.ProductQueryComplexType _query_parameters = new ProductQueryComplexType();

				QueryItem item = new QueryItem();
				item.setProductId("p01");
				item.setQty(100);
				_query_parameters.getQueryItem().add(item);

				item = new QueryItem();
				item.setProductId("p02");
				item.setQty(-200);
				_query_parameters.getQueryItem().add(item);

				item = new QueryItem();
				item.setProductId("p03");
				item.setQty(500);
				_query_parameters.getQueryItem().add(item);

				com.ttdev.biz.ProductQueryResultComplexType _query__return = port.query(_query_parameters);

				for (ResultItem resultItem : _query__return.getResultItem()) {
					System.out.println(resultItem.getProductId() + ": " + resultItem.getPrice());
				}
			} catch (QueryInvalidQty e) {
				System.out.println("Invalid qty: " + e.getFaultInfo());
			} catch (QueryInvalidProductId e) {
				System.out.println("Invalid product Id: " + e.getFaultInfo());
			}
		}

		System.exit(0);
	}

}
