/* Generated by Together */

package com.netpace.aims.bo.events;

abstract public class BaseEventHandler implements EventHandler
{
    public void handleEvent(AimsEventObject eventObj)
    {
        // Write your code here
    }
}
