/* Generated by Together */

package com.netpace.aims.bo.events;

public interface EventHandler
{
    void handleEvent(AimsEventObject eventObj);

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Observer
     * @supplierRole Concrete observers
     */

    /*# private BaseEventHandler _concreteListener; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Observer
     * @clientRole Observer
     * @supplierRole Subject
     */

    /*# private Event _event; */
}
