
package com.ch06.ejb.persist.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FibEJBService", targetNamespace = "http://persist.ejb.ch06.com/", wsdlLocation = "http://falcon:8080/FibEJBService/FibEJB?wsdl")
public class FibEJBService
    extends Service
{

    private final static URL FIBEJBSERVICE_WSDL_LOCATION;
    private final static WebServiceException FIBEJBSERVICE_EXCEPTION;
    private final static QName FIBEJBSERVICE_QNAME = new QName("http://persist.ejb.ch06.com/", "FibEJBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://falcon:8080/FibEJBService/FibEJB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIBEJBSERVICE_WSDL_LOCATION = url;
        FIBEJBSERVICE_EXCEPTION = e;
    }

    public FibEJBService() {
        super(__getWsdlLocation(), FIBEJBSERVICE_QNAME);
    }

    public FibEJBService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIBEJBSERVICE_QNAME, features);
    }

    public FibEJBService(URL wsdlLocation) {
        super(wsdlLocation, FIBEJBSERVICE_QNAME);
    }

    public FibEJBService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIBEJBSERVICE_QNAME, features);
    }

    public FibEJBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FibEJBService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Fib
     */
    @WebEndpoint(name = "FibEJBPort")
    public Fib getFibEJBPort() {
        return super.getPort(new QName("http://persist.ejb.ch06.com/", "FibEJBPort"), Fib.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Fib
     */
    @WebEndpoint(name = "FibEJBPort")
    public Fib getFibEJBPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://persist.ejb.ch06.com/", "FibEJBPort"), Fib.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIBEJBSERVICE_EXCEPTION!= null) {
            throw FIBEJBSERVICE_EXCEPTION;
        }
        return FIBEJBSERVICE_WSDL_LOCATION;
    }

}
