//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 08:38:24 AM VET 
//


package com.netpace.aims.ws.amdocs.partner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				The top level response type sent by the Content Provider
 * 				web service.
 * 			
 * 
 * <p>Java class for CreateContentProvider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateContentProvider">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errors" type="{http://api.qpass.com/cponboarding}ErrorsType" minOccurs="0"/>
 *         &lt;element name="contentProviderWorkingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cpOnboardingData" type="{http://api.qpass.com/cponboarding}CPOnboardingDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name ="CreateContentProvider", namespace="http://api.qpass.com/cponboarding")
@XmlType(name = "CreateContentProvider", propOrder = {
    "errors",
    "contentProviderWorkingName",
    "cpOnboardingData"
})
public class CreateContentProvider {

    protected ErrorsType errors;
    protected String contentProviderWorkingName;
    protected CPOnboardingDataType cpOnboardingData;

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorsType }
     *     
     */
    public ErrorsType getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorsType }
     *     
     */
    public void setErrors(ErrorsType value) {
        this.errors = value;
    }

    /**
     * Gets the value of the contentProviderWorkingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentProviderWorkingName() {
        return contentProviderWorkingName;
    }

    /**
     * Sets the value of the contentProviderWorkingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentProviderWorkingName(String value) {
        this.contentProviderWorkingName = value;
    }

    /**
     * Gets the value of the cpOnboardingData property.
     * 
     * @return
     *     possible object is
     *     {@link CPOnboardingDataType }
     *     
     */
    public CPOnboardingDataType getCpOnboardingData() {
        return cpOnboardingData;
    }

    /**
     * Sets the value of the cpOnboardingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPOnboardingDataType }
     *     
     */
    public void setCpOnboardingData(CPOnboardingDataType value) {
        this.cpOnboardingData = value;
    }

}
