//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 08:38:24 AM VET 
//


package com.netpace.aims.ws.amdocs.partner;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.netpace.aims.ws.amdocs.partner package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateContentProvider_QNAME = new QName("http://api.qpass.com/cponboarding", "CreateContentProvider");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.netpace.aims.ws.amdocs.partner
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ErrorsType }
     * 
     */
    public ErrorsType createErrorsType() {
        return new ErrorsType();
    }

    /**
     * Create an instance of {@link ProvisioningDataType }
     * 
     */
    public ProvisioningDataType createProvisioningDataType() {
        return new ProvisioningDataType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link TermsAndConditionsType }
     * 
     */
    public TermsAndConditionsType createTermsAndConditionsType() {
        return new TermsAndConditionsType();
    }

    /**
     * Create an instance of {@link CreateContentProvider }
     * 
     */
    public CreateContentProvider createCreateContentProvider() {
        return new CreateContentProvider();
    }

    /**
     * Create an instance of {@link RemittanceInformationDataType }
     * 
     */
    public RemittanceInformationDataType createRemittanceInformationDataType() {
        return new RemittanceInformationDataType();
    }

    /**
     * Create an instance of {@link InitialProfileDataType }
     * 
     */
    public InitialProfileDataType createInitialProfileDataType() {
        return new InitialProfileDataType();
    }

    /**
     * Create an instance of {@link CPOnboardingDataType }
     * 
     */
    public CPOnboardingDataType createCPOnboardingDataType() {
        return new CPOnboardingDataType();
    }

    /**
     * Create an instance of {@link ExternalInformationList }
     * 
     */
    public ExternalInformationList createExternalInformationList() {
        return new ExternalInformationList();
    }

    /**
     * Create an instance of {@link ContactDataType }
     * 
     */
    public ContactDataType createContactDataType() {
        return new ContactDataType();
    }

    /**
     * Create an instance of {@link ContentProviderDataType }
     * 
     */
    public ContentProviderDataType createContentProviderDataType() {
        return new ContentProviderDataType();
    }

    /**
     * Create an instance of {@link TaxInformationDataType }
     * 
     */
    public TaxInformationDataType createTaxInformationDataType() {
        return new TaxInformationDataType();
    }

    /**
     * Create an instance of {@link ExternalInformationData }
     * 
     */
    public ExternalInformationData createExternalInformationData() {
        return new ExternalInformationData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateContentProvider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.qpass.com/cponboarding", name = "CreateContentProvider")
    public JAXBElement<CreateContentProvider> createCreateContentProvider(CreateContentProvider value) {
        return new JAXBElement<CreateContentProvider>(_CreateContentProvider_QNAME, CreateContentProvider.class, null, value);
    }

}
