//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 08:38:24 AM VET 
//


package com.netpace.aims.ws.amdocs.partner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProvisioningDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProvisioningDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="autoApprove" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="termsAcceptanceWaived" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="revenueDistributionContractTemplateId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="revenueDistributionContractTemplateDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="purchaseAndOwnershipNotifications" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="taxNexus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxNexusWaived" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProvisioningDataType", propOrder = {
    "autoApprove",
    "termsAcceptanceWaived",
    "revenueDistributionContractTemplateId",
    "revenueDistributionContractTemplateDescription",
    "purchaseAndOwnershipNotifications",
    "taxNexus",
    "taxNexusWaived"
})
public class ProvisioningDataType {

    protected boolean autoApprove;
    @XmlElement(defaultValue = "true")
    protected boolean termsAcceptanceWaived;
    @XmlElement(required = true)
    protected String revenueDistributionContractTemplateId;
    @XmlElement(required = true)
    protected String revenueDistributionContractTemplateDescription;
    @XmlElement(defaultValue = "false")
    protected boolean purchaseAndOwnershipNotifications;
    @XmlElement(required = true)
    protected String taxNexus;
    protected boolean taxNexusWaived;

    /**
     * Gets the value of the autoApprove property.
     * 
     */
    public boolean isAutoApprove() {
        return autoApprove;
    }

    /**
     * Sets the value of the autoApprove property.
     * 
     */
    public void setAutoApprove(boolean value) {
        this.autoApprove = value;
    }

    /**
     * Gets the value of the termsAcceptanceWaived property.
     * 
     */
    public boolean isTermsAcceptanceWaived() {
        return termsAcceptanceWaived;
    }

    /**
     * Sets the value of the termsAcceptanceWaived property.
     * 
     */
    public void setTermsAcceptanceWaived(boolean value) {
        this.termsAcceptanceWaived = value;
    }

    /**
     * Gets the value of the revenueDistributionContractTemplateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueDistributionContractTemplateId() {
        return revenueDistributionContractTemplateId;
    }

    /**
     * Sets the value of the revenueDistributionContractTemplateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueDistributionContractTemplateId(String value) {
        this.revenueDistributionContractTemplateId = value;
    }

    /**
     * Gets the value of the revenueDistributionContractTemplateDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueDistributionContractTemplateDescription() {
        return revenueDistributionContractTemplateDescription;
    }

    /**
     * Sets the value of the revenueDistributionContractTemplateDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueDistributionContractTemplateDescription(String value) {
        this.revenueDistributionContractTemplateDescription = value;
    }

    /**
     * Gets the value of the purchaseAndOwnershipNotifications property.
     * 
     */
    public boolean isPurchaseAndOwnershipNotifications() {
        return purchaseAndOwnershipNotifications;
    }

    /**
     * Sets the value of the purchaseAndOwnershipNotifications property.
     * 
     */
    public void setPurchaseAndOwnershipNotifications(boolean value) {
        this.purchaseAndOwnershipNotifications = value;
    }

    /**
     * Gets the value of the taxNexus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxNexus() {
        return taxNexus;
    }

    /**
     * Sets the value of the taxNexus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxNexus(String value) {
        this.taxNexus = value;
    }

    /**
     * Gets the value of the taxNexusWaived property.
     * 
     */
    public boolean isTaxNexusWaived() {
        return taxNexusWaived;
    }

    /**
     * Sets the value of the taxNexusWaived property.
     * 
     */
    public void setTaxNexusWaived(boolean value) {
        this.taxNexusWaived = value;
    }

}
