//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 08:38:24 AM VET 
//


package com.netpace.aims.ws.amdocs.partner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TermsAndConditionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TermsAndConditionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isTermAgreed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TermsAndConditionsType", propOrder = {
    "isTermAgreed"
})
public class TermsAndConditionsType {

    protected boolean isTermAgreed;

    /**
     * Gets the value of the isTermAgreed property.
     * 
     */
    public boolean isIsTermAgreed() {
        return isTermAgreed;
    }

    /**
     * Sets the value of the isTermAgreed property.
     * 
     */
    public void setIsTermAgreed(boolean value) {
        this.isTermAgreed = value;
    }

}
