ALTER TABLE AIMS4.AIMS_JAVA_APPS
 ADD (TITLE  NVARCHAR2(400));

ALTER TABLE AIMS4.AIMS_JAVA_APPS
 ADD (SHORT_DESC  NVARCHAR2(400));

ALTER TABLE AIMS4.AIMS_JAVA_APPS
 ADD (LONG_DESC  NVARCHAR2(1000));