 Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2003);
 Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2004);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2005);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2006);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2007);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2008);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2009);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2010);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2011);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2012);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2013);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2014);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2015);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2016);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2017);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2018);
 Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2019);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2020);
Insert into AIMS_EVENT_PLACE_HOLDERS (PLACE_HOLDER_ID, EVENT_ID)
 Values (34, 2021);