ALTER TABLE AIMS_JAVA_APPS
 DROP CONSTRAINT FK_JAVA_CATEGORY_TYPE1;

ALTER TABLE AIMS_JAVA_APPS
 DROP CONSTRAINT FK_JAVA_CATEGORY_TYPE2;

ALTER TABLE AIMS_JAVA_APPS
 DROP CONSTRAINT FK_JAVA_SUB_CATEGORY_TYPE1;

ALTER TABLE AIMS_JAVA_APPS
 DROP CONSTRAINT FK_JAVA_SUB_CATEGORY_TYPE2;

ALTER TABLE AIMS_JAVA_APPS
 ADD CONSTRAINT FK_JAVA_CATEGORY_TYPE1 
 FOREIGN KEY (APP_CATEGORY_1_TYPE_ID) 
 REFERENCES AIMS_APP_CATEGORIES (CATEGORY_ID);

ALTER TABLE AIMS_JAVA_APPS
 ADD CONSTRAINT FK_JAVA_CATEGORY_TYPE2 
 FOREIGN KEY (APP_CATEGORY_2_TYPE_ID) 
 REFERENCES AIMS_APP_CATEGORIES (CATEGORY_ID);


ALTER TABLE AIMS_JAVA_APPS
 ADD CONSTRAINT FK_JAVA_SUB_CATEGORY_TYPE1 
 FOREIGN KEY (APP_SUB_CATEGORY_1_TYPE_ID) 
 REFERENCES AIMS_APP_SUB_CATEGORIES (SUB_CATEGORY_ID);

ALTER TABLE AIMS_JAVA_APPS ADD (
  CONSTRAINT FK_JAVA_SUB_CATEGORY_TYPE2 
 FOREIGN KEY (APP_SUB_CATEGORY_2_TYPE_ID) 
 REFERENCES AIMS_APP_SUB_CATEGORIES (SUB_CATEGORY_ID));

